/* SUFLE kullanıcı mesajları — m() ile okunur. TEK KAYNAK.
   sozluk.js'ten AYRI dosya, çünkü kabuklar farklı şeye ihtiyaç duyuyor:
   Mac bugün yalnız arayüz etiketlerini (I18N) kullanıyor, mesajları değil.
   Hepsini tek dosyada tutup Mac'e gömdüğümde telefona özgü metinler
   ('Ayarlar → Safari → Kamera') Mac dosyasına sızdı ve tests/52 haklı
   olarak kırıldı — Mac kullanıcısına Safari tarif edilmemeli. Kabuk
   KULLANDIĞINI gömsün. */

const MSG={
 tr:{fitNoTarget:'Önce hedef süre seç — sıfırken sığdıracak bir hedef yok',
  fitNoText:'Senaryo boş — sığdırılacak metin yok',
  fitOk:'Hız {w} WPM yapıldı — metin yaklaşık {s} sürede biter',
  fitPause:'Bu hedefe sığmaz: yalnız duraklama işaretleri {d} saniye tutuyor. İşaretleri azalt ya da hedefi büyüt.',
  fitTooFast:'Bu hedefe sığmaz: {g} WPM gerekiyor, en yüksek {u}. Metni kısalt ya da hedefi büyüt.',
  fitTooSlow:'Metin bu hedef için çok kısa: {g} WPM gerekiyor, en düşük {a}. Hız en düşüğe çekildi.',
  noCam:'Kameraya erişilemedi',camHelp:'Ayarlar → Safari → Kamera izni verin, ya da kamerasız modu kullanın.',
  recErr:'Kayıt başlatılamadı',needCam:'Önce kamerayı aç',voiceNo:'Bu tarayıcı sesle takibi desteklemiyor',
  voiceOn:'🎤 Konuşmaya başla — metin seni takip edecek',wipeStuck:'Depo cevap vermiyor, silme yarıda kaldı',takeGone:'Bu çekim artık arşivde yok',wakeMulti:'· TEK kelime olmalı, boşluklu tetik hiçbir zaman tanınmaz',wakeBad:'· Bu tetik harf ya da rakam içermiyor, tanınamaz',vlSet:'🎤 Sesle takip dili',voiceOff:'Sesle takip kapalı',micDenied:'Mikrofon izni gerekli',deleted:'Silindi',copied:'Panodan alındı',clipNo:'Panoya erişilemedi — elle yapıştır',
  end:'Metin bitti',locked:'🔒 Ekran kilitlendi',unlocked:'Kilit açıldı',newVer:'Yeni sürüm hazır — yenile',
  exported:'Yedek indirildi',imported:'📄 Dosyadan alındı',impErr:'Dosya okunamadı',noTakes:'Henüz çekim yok',
  tDone:'Metin güncellendi',tUndone:'↺ Geri alındı',toolNoop:'Değişiklik gerekmedi',
  emptyText:'Metin boş',takeKept:'Çekimlerim\'e kaydedildi',mapReset:'Varsayılan eşleme geri geldi',
  noMic:'🔇 Mikrofon yok — video sessiz kaydedilecek. Ayarlar → Kamera\'daki seviye çubuğuna bak.',
  noMicShort:'mikrofon yok',micOk:'ses geliyor ✓',micQuiet:'sessiz — konuş',
  micIosOff:'iPhone\'da kapalı (kaydı sessizleştiriyordu)',audTesting:'Deneniyor… (15 sn)',audTestWin:'✓ Sesli kaydeden biçim bulundu ve seçildi',audTestNone:'⚠️ Hiçbir biçimde ses yazılamadı',micRefresh:'🔊 Mikrofon tazeleniyor…',micFixed:'🔊 Mikrofon yenilendi — tekrar çek',
  audClip:'⚠️ Ses kırpıyor — mikrofondan uzaklaş ya da daha sakin konuş',
  takeFav:'Yıldızla', takeUnfav:'Yıldızı kaldır', takePlay:'Çekimi oynat',
  takeSrt:'Altyazı dosyasını indir', takeShare:'Çekimi paylaş veya kaydet',
  takeDel:'Çekimi sil', scDup:'Senaryoyu çoğalt', mapDel:'Tuş eşlemesini sil',
  pkgDone:'dosya tek pakette hazır', noTake:'Önce bir çekim yap',
  takeNote:'Çekim notu yaz', takeNotePrompt:'Bu çekim için not (neden iyi ya da kötü):',
  verSwitch:'Senaryonun diğer sürümüne geç', verSwitched:'Sürüm', verEmpty:'Önce bu sürüme metin yaz',
  dlgBusy:'⛔ Kayıt sürerken bu pencere açılamaz — sufle ve görüntü donar',
  audClipShort:'ses kırpıyor',audLowShort:'ses kısık',audOkShort:'ses iyi',
  recOn:'KAYITTA',recPaused:'DURAKLADI',recPausedInfo:'⏸ Kayıt duraklatıldı — ⏺ ile aynı videoya devam edersin',
  recResumed:'⏺ Kayıt devam ediyor',pauseNo:'Bu cihazda kayıt duraklatılamıyor',
  resetSure:'Emin misin? Tekrar bas',resetDone:'Ayarlar varsayılana döndü',
  trimNo:'Bu cihaz uygulama içinde kesmeyi desteklemiyor — videoyu Fotoğraflar\'a kaydedip oradan kırp (kalite kaybı da olmaz)',
  notMp4:'Video MP4 değil — Fotoğraflar kabul etmeyebilir',
  shareFail:'Paylaşım açılamadı',
  noFileShare:'Bu tarayıcı dosya paylaşamıyor — Safari\'de aç',
  noShare:'Bu tarayıcıda paylaşım yok — Safari\'de aç',
  rewound:'↺ Metin başa sarıldı',
  toFilesDone:'📁 Dosyalar\'a indi — Dosyalar uygulamasında aç, oradan Fotoğraflar\'a taşıyabilirsin',
  savedFiles:'Dosyalar\'a indirildi → Dosyalar uygulamasında videoyu aç → Paylaş → Videoyu Kaydet',trimShort:'Seçim çok kısa',trimming:'Kesiliyor…',trimDone:'✂️ Kesildi',trimFail:'Kesme başarısız — Fotoğraflar\'da kırpmayı dene',
  audioFallback:'Ham ses açılamadı, normal sese geçildi',
  noCaps:'Altyazı üretilemedi — kayıt sırasında sufle akmamış',capsMade:'altyazı satırı',
  needsComp:'Kompozit açıldı — bu özellik ancak kompozit görüntü üstünde çalışır',
  camDenied:'📷 Kamera izni verilmemiş — ',
  camBusy:'📷 Kamera başka uygulamada açık — FaceTime/Zoom/Kamera\'yı kapat ve tekrar dene',
  camNone:'📷 Uygun kamera bulunamadı — çözünürlüğü 720p yapıp tekrar dene',
  delConfirm:'⚠️ Emin misin? Tekrar bas',deletedUndo:'Silindi — ↺ ile geri getirebilirsin',
  restored:'↺ Senaryo geri geldi',vidDied:'⛔ GÖRÜNTÜ KESİLDİ — ses sürüyor ama video durdu, kaydı bitir',audDied:'⛔ SES KESİLDİ — görüntü sürüyor ama mikrofon gitti, kaydı bitir',fxDead:'⛔ Ses işleme durdu — bundan sonrası SESSİZ kaydediliyor, kaydı bitir',fxBack:'🔊 Ses işleme geri geldi',marksReset:'Metin değişti — bölüm ✓ işaretleri ve zorlanma haritası sıfırlandı',vadOffRec:'🫁 Nefesle akış kayıt boyunca kapatıldı (iPhone sesi korunuyor)',recBusy:'Kayıt sürerken senaryo değiştirilemez — önce kaydı durdur',micGone:'🎙 Seçili mikrofon bulunamadı (çıkarılmış olabilir) — dahili mikrofona dönüldü',noBackup:'Otomatik yedek yok (birkaç düzenleme sonra oluşur)',restoredBackup:'🛟 Yedekten dönüldü —',keyPicked:'Perde rengi ölçüldü →',keyPickFail:'Renk ölçülemedi',longScript:'⚠️ Metin çok uzun — sufle takılabilir, bölümlere ayırmayı düşün',wiped:'yıldızsız çekim silindi',nothingWipe:'Silinecek yıldızsız çekim yok',noMatch:'Eşleşen senaryo yok',voiceSilentCam:'🎤 Tanıma açıldı ama hiç ses gelmiyor — kamera açıkken mikrofonu paylaşmak iPhone\'da tanımayı susturabiliyor. Kamerayı kapatıp "Kamerasız sadece sufle" ile dene.',voiceSilent:'🎤 Tanıma açıldı ama hiç ses gelmiyor — mikrofon izni verilmemiş ya da mikrofonu başka bir uygulama tutuyor olabilir. Ayarlar → 🎤 Mikrofonu ve tanımayı sına ile kesin sonucu gör.',mapIn:'🎮 Kumanda profili yüklendi —',mapInBad:'Bu dosya bir kumanda profili değil',mapInEmpty:'Dosyada tanınan tuş eşlemesi yok — profil değişmedi',mapInErr:'Dosya okunamadı',
  jsErr:'⚠️ Bir şey ters gitti — ayrıntı: Ayarlar → Diğer → Cihaz uyumluluğu',
  lsFull:'⚠️ Depo dolu — senaryo KAYDEDİLEMEDİ. Arka plan görselini kaldır ya da kullanmadığın senaryoları sil.',lsFreed:'🧹 Silinen senaryolar kalıcı olarak temizlendi ve senaryon kaydedildi',
  cfgBroken:'⚠️ Ayar dosyası bozuktu, varsayılana dönüldü (bozuk kopya saklandı)',
  archFail:'⚠️ Çekim arşive yazılamadı (depo dolu) — video elinde, hemen paylaş/kaydet',archWarnTxt:'⚠️ Bu çekim arşive yazılamadı — depoda yer yok. Video şu an yalnızca burada: kapatmadan önce paylaş ya da yer açıp tekrar dene.',archWipeBtn:'🗑 Yıldızsız çekimleri sil ve tekrar dene',archWipeSure:'Emin misin? Geri alınamaz —',archRetryOk:'✓ Yer açıldı, çekim arşive yazıldı',archRetryFail:'Hâlâ yazılamadı — videoyu kapatmadan paylaş',archNoWipe:'Silinecek yıldızsız çekim yok — videoyu kapatmadan paylaş',
  recDied:'⛔ Kayıt yarıda kesildi — o ana kadarki bölüm duruyor',
  recNoStart:'⛔ Kayıt başlamadı — kamerayı kapatıp aç, sonra tekrar dene',
  recNoData:'⚠️ Kayıttan veri gelmiyor — durdurup tekrar başlat',
  camBusyRec:'⛔ Kayıt sürerken kamera/mikrofon değiştirilemez — önce kaydı durdur',compBusyRec:'⛔ Kayıt sürerken kompozit açılıp kapatılamaz — kayda giden görüntü çekim başında belirleniyor',nextTakeOnly:'ℹ️ Bu ayar SONRAKİ çekimde geçerli — süren kayda yansımıyor',
  glLostRec:'⛔ Kompozit kayıt sırasında koptu — çekim burada bitirildi, o ana kadarki kısım arşivde',
  glLost:'⚠️ Kompozit koptu (bellek) — kompoziti kapatıp aç',
  glBack:'✅ Kompozit geri geldi',
  camBack:'✅ Kamera yeniden bağlandı',
  voiceDied:'⛔ Sesle takip bağlantısı koptu — 🎤 ile tekrar aç',
  compAudioWarn:'⚠️ iPhone\'da kompozit açıkken ses kaydedilmeyebilir — sesli çekimde kapalı tut',
  compNo:'Bu cihaz/tarayıcı kompozit kaydı desteklemiyor',compFallback:'Kompozit kayıt kurulamadı, ham kamerayla kaydediliyor',
  bgSet:'Arka plan görseli yüklendi',bgCleared:'Arka plan görseli kaldırıldı',
  bgTooBig:'Görsel çok büyük — daha küçük bir görsel seç',bgDosyaBuyuk:'Görsel dosyası çok büyük — 25 MB altında bir görsel seç',tiltOk:'📐 Eğim ölçümü açık',tiltNo:'Bu cihazda eğim ölçülemiyor',resumed:'↩︎ Kaldığın yerden',
  /* Cihaz dışı yedek (C.2) */
  bkDone:'Yedeklendi — dosyayı güvenli bir yerde sakla',bkEmpty:'Dosyada senaryo yok',bkBad:'Dosya okunamadı — Sufle yedeği mi?',bkAdded:'senaryo eklendi',
  /* Odak/pozlama kilidi (D.2) */
  lockNo:'Bu kamera kilitlemeye izin vermiyor',
  /* .docx içe aktarma (D.1) */
  docxBad:'Word dosyası okunamadı — gerçekten .docx mi?'},
 en:{fitNoTarget:'Pick a target duration first — there is nothing to fit to at zero',
  fitNoText:'The script is empty — there is no text to fit',
  fitOk:'Pace set to {w} WPM — the script now takes about {s}',
  fitPause:'It does not fit: the pause marks alone take {d} seconds. Remove some marks or raise the target.',
  fitTooFast:'It does not fit: {g} WPM would be needed and the maximum is {u}. Shorten the script or raise the target.',
  fitTooSlow:'The script is too short for this target: {g} WPM would be needed and the minimum is {a}. Pace set to the minimum.',
noCam:'Camera unavailable',camHelp:'Allow camera in Settings → Safari, or use prompter-only mode.',
  recErr:'Could not start recording',needCam:'Open the camera first',voiceNo:'This browser has no speech recognition',
  voiceOn:'🎤 Start talking — the script will follow you',wipeStuck:'Storage is not responding, deletion stopped early',takeGone:'That take is no longer in the archive',wakeMulti:'· Must be ONE word, a trigger with spaces is never recognised',wakeBad:'· This trigger has no letters or digits, so it can never match',vlSet:'🎤 Voice-follow language',voiceOff:'Voice follow off',micDenied:'Microphone permission needed',deleted:'Deleted',copied:'Pasted from clipboard',clipNo:'Clipboard blocked — paste manually',
  end:'End of script',locked:'🔒 Screen locked',unlocked:'Unlocked',newVer:'New version ready — reload',
  exported:'Backup downloaded',imported:'📄 Imported from file',impErr:'Could not read file',noTakes:'No takes yet',
  tDone:'Script updated',tUndone:'↺ Undone',toolNoop:'Nothing to change',
  emptyText:'Script is empty',takeKept:'Saved to My takes',mapReset:'Default key map restored',
  noMic:'🔇 No microphone — the video will be silent. Check the level bar in Settings → Camera.',
  recOn:'RECORDING',recPaused:'PAUSED',recPausedInfo:'⏸ Paused — press ⏺ to continue the same video',
  recResumed:'⏺ Recording again',pauseNo:'This device cannot pause recording',
  resetSure:'Sure? Press again',resetDone:'Settings reset to defaults',
  trimNo:'This device cannot trim in-app — save to Photos and trim there (lossless too)',
  notMp4:'Not MP4 — Photos may refuse it',
  shareFail:'Could not open the share sheet',
  noFileShare:'This browser cannot share files — open in Safari',
  noShare:'No sharing in this browser — open in Safari',
  rewound:'↺ Rewound to the start',
  toFilesDone:'📁 Saved to Files — open it there to move it into Photos',
  savedFiles:'Downloaded to Files → open it in the Files app → Share → Save Video',trimShort:'Selection too short',trimming:'Cutting…',trimDone:'✂️ Trimmed',trimFail:'Trim failed — try trimming in Photos',
  noMicShort:'no mic',micOk:'audio ✓',micQuiet:'silent — talk',
  micIosOff:'off on iPhone (it was silencing recordings)',audTesting:'Testing… (15s)',audTestWin:'✓ Found a format that records audio',audTestNone:'⚠️ No format produced audio',micRefresh:'🔊 Refreshing microphone…',micFixed:'🔊 Microphone refreshed — record again',
  audClip:'⚠️ Audio is clipping — back off the mic or speak softer',
  takeFav:'Star this take', takeUnfav:'Remove star', takePlay:'Play take',
  takeSrt:'Download subtitle file', takeShare:'Share or save take',
  takeDel:'Delete take', scDup:'Duplicate script', mapDel:'Delete key mapping',
  pkgDone:'files bundled', noTake:'Record a take first',
  takeNote:'Add take note', takeNotePrompt:'Note for this take (why it was good or bad):',
  verSwitch:'Switch to the other script version', verSwitched:'Version', verEmpty:'Write something in this version first',
  dlgBusy:'⛔ Cannot open this dialog while recording — the prompter and video would freeze',
  audClipShort:'clipping',audLowShort:'too quiet',audOkShort:'audio ok',
  audioFallback:'Raw audio unavailable, switched to normal audio',
  noCaps:'No captions — the prompter did not run while recording',capsMade:'caption lines',
  needsComp:'Composite turned on — this feature only works on the composite image',
  camDenied:'📷 Camera permission denied — ',
  camBusy:'📷 Camera is in use by another app — close FaceTime/Zoom/Camera and retry',
  camNone:'📷 No suitable camera — try 720p and retry',
  delConfirm:'⚠️ Sure? Tap again',deletedUndo:'Deleted — restore it with ↺',
  restored:'↺ Script restored',vidDied:'⛔ VIDEO STOPPED — audio continues but video died, end the take',audDied:'⛔ AUDIO STOPPED — video continues but the microphone is gone, end the take',fxDead:'⛔ Audio processing stopped — the rest is being recorded SILENT, end the take',fxBack:'🔊 Audio processing recovered',marksReset:'Script changed — section ✓ marks and struggle map were cleared',vadOffRec:'🫁 Breath flow paused during recording (protects iPhone audio)',recBusy:'Cannot switch scripts while recording — stop the recording first',micGone:'🎙 Selected microphone is gone — switched back to the built-in one',noBackup:'No auto-backup yet (created after a few edits)',restoredBackup:'🛟 Restored from backup —',keyPicked:'Screen colour sampled →',keyPickFail:'Could not sample colour',longScript:'⚠️ Script is very long — the prompter may stutter; consider splitting it',wiped:'unstarred takes deleted',nothingWipe:'No unstarred takes to delete',noMatch:'No matching script',voiceSilentCam:'🎤 Recognition started but no audio is arriving — sharing the mic with the camera can silence recognition on iPhone. Turn the camera off and try "Prompter only, no camera".',voiceSilent:'🎤 Recognition started but no audio is arriving — permission may be missing, or another app holds the mic. Use Settings → 🎤 Test mic and recognition for a definite answer.',mapIn:'🎮 Remote profile loaded —',mapInBad:'This file is not a remote profile',mapInEmpty:'No usable key mapping in the file — the profile is unchanged',mapInErr:'Could not read the file',
  jsErr:'⚠️ Something went wrong — details in Settings → More → Device compatibility',
  lsFull:'⚠️ Storage full — script was NOT saved. Remove the background image or delete scripts you no longer need.',lsFreed:'🧹 Deleted scripts were purged and your script was saved',
  cfgBroken:'⚠️ Settings file was corrupt, reset to defaults (broken copy kept)',
  archFail:'⚠️ Take could not be archived (storage full) — the video is here, share it now',archWarnTxt:'⚠️ This take could not be archived — storage is full. The video exists only here right now: share it before closing, or free space and retry.',archWipeBtn:'🗑 Delete unstarred takes and retry',archWipeSure:'Are you sure? This cannot be undone —',archRetryOk:'✓ Space freed, take archived',archRetryFail:'Still could not archive — share the video before closing',archNoWipe:'No unstarred takes to delete — share the video before closing',
  recDied:'⛔ Recording stopped early — what was captured is kept',
  recNoStart:'⛔ Recording did not start — close and reopen the camera, then retry',
  recNoData:'⚠️ No data coming from the recorder — stop and start again',
  camBusyRec:'⛔ Cannot change camera or microphone while recording — stop the take first',compBusyRec:'⛔ Cannot switch the composite on or off while recording — the recorded image is fixed when the take starts',nextTakeOnly:'ℹ️ This setting applies to the NEXT take — it does not affect the take in progress',
  glLostRec:'⛔ Composite dropped mid-recording — the take was ended here; everything up to that point is archived',
  glLost:'⚠️ Composite dropped (memory) — turn composite off and on',
  glBack:'✅ Composite restored',
  camBack:'✅ Camera reconnected',
  voiceDied:'⛔ Voice follow lost its connection — turn it on again with 🎤',
  compAudioWarn:'⚠️ iOS may drop audio while composite is on — keep it off for spoken takes',
  compNo:'This device/browser does not support composite recording',compFallback:'Composite recording failed, using the raw camera',
  bgSet:'Background image loaded',bgCleared:'Background image removed',
  bgTooBig:'Image too large — pick a smaller one',bgDosyaBuyuk:'Image file too large — pick one under 25 MB',tiltOk:'📐 Tilt measuring on',tiltNo:'Tilt is not available on this device',resumed:'↩︎ Resumed where you left off',
  /* Cihaz dışı yedek (C.2) */
  bkDone:'Backed up — keep the file somewhere safe',bkEmpty:'No scripts in the file',bkBad:'Could not read the file — is it a Sufle backup?',bkAdded:'scripts added',
  /* Odak/pozlama kilidi (D.2) */
  lockNo:'This camera does not allow locking',
  /* .docx içe aktarma (D.1) */
  docxBad:'Word file could not be read — is it really a .docx?'}
};
