/* SUFLE sözlüğü — TEK KAYNAK. İki kabuğa da derle.py gömer.
   Telefondan olduğu gibi alındı; TR/EN paritesi 240/240 ölçülmüştü ve
   taşımada bozulmadığı diff ile kanıtlandı. Mac bugüne dek Türkçeye
   gömülüydü (data-i18n sayısı 0) — İngilizce desteği buradan gelecek.

   I18N = arayüz etiketleri (t() ve data-i18n)
   MSG  = kullanıcıya gösterilen mesajlar (m())
   Yeni anahtar eklerken TR ve EN'e BİRLİKTE ekle; denetim.py parite farkını
   yakalıyor ama eksik çeviri kullanıcıya boş etiket olarak görünür. */

const I18N={
 tr:{lookHere:'buraya bak',tapNote:'▶︎ başlatmak için ekrana dokun · yukarı-aşağı sürükle = konum · − + ile hız (sağ kenardan da sürükleyebilirsin)',
  lockedPill:'🔒 kilitli — iki kez dokun',introP:'Telefonun önünde okurken doğrudan kaydet. Yazı kameranın hemen altında akar; göz teması bozulmaz.',
  startCam:'Kamerayı Aç & Başla',startNoCam:'Kamerasız sadece sufle',help:'Nasıl kullanılır?',install:'📲 Ana ekrana ekle',settings:'Ayarlar',
  tabRead:'Okuma',tabLook:'Görünüm',tabCam:'Kamera',tabMore:'Diğer',speedWpm:'Hız — WPM (dakikada kelime)',
  speedHint:'Doğal konuşma 120–160 WPM. Metnin tahmini süresi aşağıda.',eyeLine:'👁 Okuma çizgisi konumu (kameraya yaklaştır)',
  fontSize:'Yazı boyutu',lineH:'Satır aralığı',margin:'Kenar boşluğu',tgEye:'🎯 Okuma çizgisi',tgDim:'🌗 Odak karartma',
  tgHl:'✨ Kelime vurgusu',tgFade:'🫥 Okunanı soluklaştır',tgPause:'🫁 Paragraf sonunda nefes durağı',tgCount:'⏱ 3-2-1 geri sayım',
  font:'Yazı tipi',fSystem:'Sistem',fSerif:'Serif',fRound:'Yumuşak',fDys:'Disleksi',weight:'Kalınlık',tracking:'Harf aralığı',
  align:'Hizalama',aCenter:'Orta',aLeft:'Sol',
  caseL:'Harf düzeni (yalnız görünüm)',caseNone:'Normal',caseUp:'BÜYÜK',caseLow:'küçük',
  caseHint:'Metni değiştirmez — altyazı ve senaryo olduğu gibi kalır.',
  tClean:'🧹 Temizle',tJoin:'↩︎ Satırları birleştir',tCase:'Aa Cümle düzeni',toolHint:'Araçlar senaryoyu değiştirir — ↺ ile geri alınır. Cümle düzeni özel isimleri de küçültür, onları elle düzelt.',
  tBreath:'🫁 Nefes işareti',tNum:'🔢 Sayıları yaz',tUndo:'↺ Geri al',textColor:'Yazı rengi',cWhite:'Beyaz',cYellow:'Sarı',cGreen:'Yeşil',cBlack:'Siyah',
  cNavy:'Lacivert',bgColor:'Zemin (kamerasız modda)',scrim:'Kamera üstü karartma (okunurluk)',
  tgMirror:'🪞 Yazıyı aynala (cam rig / beam splitter)',tgFlip:'🔃 Yazıyı dikey çevir',tgShadow:'🌑 Yazı gölgesi',
  quality:'Kayıt kalitesi',qHint:'Cihaz desteklemezse en yakın çözünürlüğe düşer.',frameGuide:'Çerçeve kılavuzu',aspNone:'Kapalı',
  zoom:'Yakınlaştırma',tgBack:'🔄 Arka kamera',tgTorch:'🔦 Işık (fener)',tgGrid:'▦ Üçler kuralı + baş boşluğu',
  tgRaw:'🎚 Ham ses (hiç işleme yapma)',
  rawHint:'Ham ses daha doğal tınlar ama bazı iPhone\'larda sorun çıkarır — ses gelmiyorsa kapalı bırakın.',
  lightTitle:'💡 Işık ve çerçeve denetçisi',lightBtn:'🔎 Şimdi denetle',tiltBtn:'📐 Eğim ölç',
  lightHint:'Bu sekme açıkken saniyede bir ölçüyor. Yüz bölgesinin parlaklığını kenarlarla karşılaştırıp arkadan ışığı, patlamayı ve kontrast eksikliğini yakalar.',
  compTitle:'🎛 Kompozit kayıt (gerçek kırpma + yeşil ekran)',tgComp:'Kompoziti aç',
  compHint:'Kayıt kameradan değil işlenmiş tuvalden alınır: seçtiğin oran gerçekten kırpılır ve yeşil ekran çalışır. Pil/ısı maliyeti vardır, gerekmedikçe kapalı tut.',
  tgBurn:'💬 Altyazıyı videoya göm',capSize:'Altyazı boyutu',capPos:'Altyazı konumu',cpBottom:'Alt',cpMiddle:'Orta',
  burnHint:'Okuduğun cümle videonun üstüne yazılır — ayrı altyazı dosyası yüklemene gerek kalmaz. Kompozit açık olmalı.',
  tgChroma:'🟩 Yeşil ekran (chroma key)',keyColor:'Perde rengi',kGreen:'Yeşil',kBlue:'Mavi',kCream:'Krem',
  keySim:'Eşik (ne kadarı silinsin)',keySmooth:'Kenar yumuşaklığı',newBg:'Yeni arka plan',
  spill:'Saçak temizliği (despill)',bkColor:'Düz renk',bkStudio:'Stüdyo',bkWarm:'Sıcak',bkCool:'Soğuk',
  bkBokeh:'Bokeh',bkBrand:'Marka',bkImage:'Görsel',
  bgPick:'🖼 Görsel seç',bgClear:'✕ Görseli kaldır',
  chromaHint:'Yeşil ekran olmadan arka plan değiştirilemez — kişiyi arka plandan ayırmak için yapay zekâ modeli gerekir, o telefonda çok ağır. Düz renkli bir perde/duvar yeter (kırışıksız ve eşit aydınlatılmış olsun).',
  capOffset:'💬 Altyazı kayması (sn)',
  capHint:'Altyazı senaryodan üretilir, konuşma tanıma kullanılmaz — yazım her zaman doğrudur. Zamanlama kelimenin okuma çizgisinden geçtiği andır; erken/geç çıkıyorsa buradan kaydır.',
  tgBionic:'⚡ Biyonik okuma (kelime başları kalın)',
  tgSection:'🎬 Bölüm sonunda dur (bölüm bölüm çek)',
  secHint:'Açıkken sufle her # bölümünün sonunda durur; o bölümü çekip kaydı kapatınca bölüm ✓ işaretlenir. Senaryolar sayfasında hangi bölümü çektiğini görürsün.',checkBtn:'🔍 Konuşulabilirlik denetimi',diffBtn:'🗺 Zorlanma haritası',
  spLabel:'HIZ · WPM',readyTitle:'✅ Çekime hazır mıyım?',readyAgain:'↻ Tekrar bak',readyGo:'● Çekime başla',
  band:'👁 Okuma şeridi (göz teması)',bAll:'Tümü',b1:'1 satır',b2:'2 satır',b3:'3 satır',
  eyeRecipe:'👁 Göz teması ayarını uygula',dist:'📏 Yüz–telefon mesafesi (cm)',
  mode:'🎯 Çekim modu',mFree:'Serbest',mStory:'Story',mPost:'IG Gönderi',mVideo:'YouTube',
  tgSafe:'🚫 Platform arayüz alanlarını göster',
  micLevel:'🎙 Mikrofon seviyesi',fixAudio:'🔊 Sesi onar (mikrofonu tazele)',
  audTest:'🔎 Ses testi (cihaza yaptır)',
  audTestHint:'Telefonun hangi kayıt biçiminde ses yazdığını tek tek dener ve çalışanı kalıcı seçer. Yaklaşık 15 saniye sürer.',
  fixAudioHint:'Çekimde ses çıkmıyorsa buna bas: kamera ve mikrofon sıfırdan açılır.',
  tgSafeAudio:'🛡 Güvenli ses modu (iPhone için önerilir)',
  safeAudioHint:'Kamerayı en sade ayarlarla açar (çözünürlük isteği yok). iPhone\'da sessiz kayıt sorununu çözen ayar budur; kapatırsan yüksek çözünürlük istenir.',
  micHint:'Konuş — çubuk oynamıyorsa ses kaydedilmez. Oynamıyorsa: iOS Ayarlar → Safari → Mikrofon izni, ya da mikrofonu tutan başka bir uygulamayı kapat.',
  noMicShort:'🔇 mikrofon yok — ses kaydedilmiyor',
  reopenCam:'🔁 Kamerayı yeniden başlat',targetDur:'Hedef süre (pacing)',targetHint:'Hedef verirsen üstteki rozet geri/ileri olduğunu gösterir.',
  voiceLang:'Sesle takip dili',tgLock:'🔒 Kayıtta ekranı kilitle',tgKeepAwake:'☀️ Ekranı uyanık tut',tgHideUI:'🫧 Kayıtta düğmeleri gizle',
  resetAll:'↺ Ayarları varsayılana döndür',resetHint:'Yalnız ayarları sıfırlar — senaryoların ve çekimlerin durur.',
  devBtn:'📱 Cihaz uyumluluğu',backup:'Yedekle / Geri yükle',export:'⬆︎ Dışa aktar',import:'⬇︎ İçe aktar',takes:'🎞 Çekimlerim',scripts:'Senaryolar',
  newScript:'＋ Yeni',paste:'📋 Yapıştır',fromFile:'📄 Dosya',sections:'🔖 Bölümler — dokun, oraya atla',
  title:'Başlık',text:'📝 Metin',
  markHint:'# başlık · [not] · *vurgu* · / kısa dur · // uzun dur · (2) bekle · kelime{o-ku-nuş} telaffuz',delete:'🗑 Sil',apply:'✓ Uygula',
  takesHint:'Çekimler telefonun tarayıcı deposunda tutulur. Fotoğraflar\'a eklemek için "Kaydet / Paylaş"a bas.',
  takeReady:'Çekim hazır',deleteRedo:'🗑 Sil',keep:'Kapat',saveShare:'📤 Paylaş / Kaydet',toFiles:"📁 Dosyalar'a Kaydet",
  editBtn:'✂️ Düzenle',trimSteps:'✂️ Kırpmak istersen: önce <b>Fotoğraflara Kaydet</b> → <b>Fotoğraflar</b> uygulamasında videoyu aç → sağ üstten <b>Düzenle</b> → alttaki şeridin uçlarından çek. Orada kırpmak kalite kaybı da yapmaz.',trimStart:'✂️ Baştan kes',trimEnd:'✂️ Sondan kes',
  trimPrev:'▶︎ Seçimi oynat',trimGo:'✂️ Kes ve uygula',
  saveHint:'Açılan menüde <b>“Videoyu Kaydet”</b>e dokun — video Fotoğraflar\'a gider. Çekim zaten uygulamanın <b>Çekimlerim</b> arşivinde duruyor, oradan da ulaşabilirsin.',
  remote:'🎛 Uzaktan kumanda',
  remoteHint:'Bluetooth sunum kumandası, sayfa çevirici pedal veya klavye — telefonla eşleştir, aşağıdaki tuşa bas, ne yapacağını seç.',
  lastKeyL:'Gelen son tuş',learnStart:'🎯 Tuş öğret',mapReset:'↺ Varsayılana dön',mapList:'Eşleme tablosu',
  ssUsed:'Son kullanılan',ssName:'Ada göre',ssLen:'Uzunluğa göre',
  csClean:'Sade',csSocial:'Sosyal (büyük, ortada)',capMaxW:'Satırda en fazla kelime',
  profL:'⚡ Hazır kurulum',pfReels:'Reels',pfYT:'YouTube',pfTalk:'Sunum',
  profHint:'Tek dokunuşla o iş için denenmiş ayar takımı: hız, oran, okuma şeridi, ses ve görüntü filtresi birlikte ayarlanır. Sonrasında istediğini değiştirebilirsin.',
  vadL:'🫁 Nefesle akış',tgVad:'Konuşmayı kesince sufle dursun',vadSens:'Duyarlılık',
  tgHicon:'◐ Yüksek kontrast',newsTitle:'🆕 Ne değişti?',capBtnL:'💬 Altyazı dosyası',pkgBtnL:'📦 Yayın paketi',setFindPh:'🔎 Ayarlarda ara…',restoreBk:'🛟 Otomatik yedekten dön',vfxTitle:'🎨 Görüntü filtresi',vfxOff:'Kapalı',vfxNat:'Doğal',vfxBright:'Aydınlık',vfxWarm:'Sıcak',vfxCrisp:'Net',vfxLow:'Az ışık',
  vfxHint:'Filtre yalnız <b>kompozit açıkken</b> videoya işlenir — kompozit kapalıysa görüntü ham kaydedilir. Az ışıkta keskinlik gürültüyü büyüttüğü için o hazır ayarda kasten düşük tutuldu.',fxTitle:'🎚 Ses Stüdyosu',fxOff:'Kapalı',fxVoice:'Konuşma',fxNoisy:'Gürültülü ortam',fxStudio:'Stüdyo',
  fxGate:'Gürültü kapısı',fxPres:'Netlik (anlaşılırlık)',fxWarm:'Tok ses (gövde)',
  fxAdvHint:'Kapı: bu eşiğin altındaki sesler (klima, uzaktaki konuşma, klavye) kısılır. Çok yüksek tutarsan kendi cümle başların da kesilir.',pickKey:'🎯 Perdenin rengini kameradan ölç',tgMask:'🎭 Maske önizlemesi (silinen yer mor)',bkSoft:'Yumuşak',brL:'Video kalitesi / dosya boyutu',brLow:'Küçük dosya',brMid:'Dengeli',brHigh:'En iyi',micSel:'🎙 Mikrofon',tgEyeLine:'👁 Göz hattı kılavuzu (üçte bir)',
  eyeLineHint:'Gözlerin üstteki çizgide olsun — sinemada ve haberde kullanılan kural. Çok yukarıdaysan kafanın üstünde boşluk kalır, çok aşağıdaysan çene kesilir.',tap1:'Tek basış',tap2:'Çift basış',wakeWordL:'Kendi tetik kelimen',mapExport:'⬆︎ Profili dışa aktar',mapImport:'⬇︎ Profili içe aktar',
  noRemoteHint:'Kumandan yok mu? Ekranın <b>sol yarısına</b> çift dokunuş kilit, <b>alt şeritteki −/+</b> hız, <b>parmakla sürükleme</b> konum içindir. 🎤 sesli komut da aynı işi görür.',tSplit:'🪓 Uzun satırları böl',sortNew:'Yeni önce',sortBig:'Büyük önce',sortLong:'Uzun önce',
  wipeTakes:'🗑 Yıldızsızları sil',voiceTest:'🎤 Mikrofonu ve tanımayı sına',findPh:'🔎 Senaryolarda ara…',undoDel:'↺ Silineni geri getir',
  voiceCmdL:'🗣 Sesli komut',voiceCmdT:'"sufle başla / dur / hızlan / yavaşla / başa dön / kaydet"',
  voiceCmdHint:'🎤 düğmesi açıkken çalışır. Komutlar metne karışmaz — "sufle" ile başlayan iki kelimelik kalıplar komut sayılır.'},
 en:{lookHere:'look here',tapNote:'▶︎ tap to start · drag up/down = position · − + for speed (or drag the right edge)',
  lockedPill:'🔒 locked — double tap',introP:'Record straight from your phone while you read. Text scrolls right under the lens so eye contact holds.',
  startCam:'Open Camera & Start',startNoCam:'Prompter only (no camera)',help:'How to use',install:'📲 Add to home screen',settings:'Settings',
  tabRead:'Reading',tabLook:'Look',tabCam:'Camera',tabMore:'More',speedWpm:'Speed — WPM (words per minute)',
  speedHint:'Natural speech is 120–160 WPM. Estimated duration below.',eyeLine:'👁 Reading line position (closer to lens)',
  fontSize:'Font size',lineH:'Line height',margin:'Side margin',tgEye:'🎯 Reading line',tgDim:'🌗 Focus dimming',
  tgHl:'✨ Word highlight',tgFade:'🫥 Fade read words',tgPause:'🫁 Breath pause at paragraphs',tgCount:'⏱ 3-2-1 countdown',
  font:'Typeface',fSystem:'System',fSerif:'Serif',fRound:'Rounded',fDys:'Dyslexia',weight:'Weight',tracking:'Letter spacing',
  align:'Alignment',aCenter:'Center',aLeft:'Left',
  caseL:'Letter case (display only)',caseNone:'Normal',caseUp:'UPPER',caseLow:'lower',
  caseHint:'Does not change the script — captions stay as written.',
  tClean:'🧹 Clean up',tJoin:'↩︎ Join lines',tCase:'Aa Sentence case',toolHint:'Tools rewrite the script — ↺ undoes the last one. Sentence case also lowercases proper nouns; fix those by hand.',
  tBreath:'🫁 Breath marks',tNum:'🔢 Numbers to words',tUndo:'↺ Undo',textColor:'Text color',cWhite:'White',cYellow:'Yellow',cGreen:'Green',cBlack:'Black',
  cNavy:'Navy',bgColor:'Background (no-camera mode)',scrim:'Dim over camera (legibility)',
  tgMirror:'🪞 Mirror text (beam splitter rig)',tgFlip:'🔃 Flip text vertically',tgShadow:'🌑 Text shadow',
  quality:'Recording quality',qHint:'Falls back to the closest resolution the device supports.',frameGuide:'Frame guide',aspNone:'Off',
  zoom:'Zoom',tgBack:'🔄 Rear camera',tgTorch:'🔦 Torch',tgGrid:'▦ Rule of thirds + headroom',
  tgRaw:'🎚 Raw audio (no noise suppression)',
  rawHint:'Raw sounds more natural but breaks on some iPhones — leave it off if you get no sound.',
  lightTitle:'💡 Light & framing inspector',lightBtn:'🔎 Check now',tiltBtn:'📐 Measure tilt',
  lightHint:'Samples once per second while this tab is open. Compares face-area brightness with the edges to catch backlight, blown highlights and low contrast.',
  compTitle:'🎛 Composite recording (real crop + green screen)',tgComp:'Enable composite',
  compHint:'Recording comes from a processed canvas instead of the raw camera: your chosen ratio is truly cropped and green screen works. Costs battery/heat — leave it off unless needed.',
  tgBurn:'💬 Burn captions into the video',capSize:'Caption size',capPos:'Caption position',cpBottom:'Bottom',cpMiddle:'Middle',
  burnHint:'The sentence you are reading is drawn on the video — no separate subtitle file needed. Composite must be on.',
  tgChroma:'🟩 Green screen (chroma key)',keyColor:'Screen colour',kGreen:'Green',kBlue:'Blue',kCream:'Cream',
  keySim:'Threshold (how much is removed)',keySmooth:'Edge softness',newBg:'New background',
  spill:'Spill suppression',bkColor:'Solid',bkStudio:'Studio',bkWarm:'Warm',bkCool:'Cool',
  bkBokeh:'Bokeh',bkBrand:'Brand',bkImage:'Image',
  bgPick:'🖼 Pick image',bgClear:'✕ Remove image',
  chromaHint:'Without a green screen the background cannot be replaced — separating a person from the background needs an AI model, which is far too heavy on a phone. A plain, evenly lit sheet or wall is enough.',
  capOffset:'💬 Caption offset (s)',
  capHint:'Captions come from the script, not speech recognition — spelling is always right. Timing is when each word crossed the reading line; shift it here if they appear early or late.',
  tgBionic:'⚡ Bionic reading (bold word starts)',
  tgSection:'🎬 Stop at section end (shoot section by section)',
  secHint:'The prompter stops at the end of every # section; finish that take and the section gets a ✓. The Scripts sheet shows what you have shot.',checkBtn:'🔍 Speakability check',diffBtn:'🗺 Struggle map',
  spLabel:'SPEED · WPM',readyTitle:'✅ Am I ready to shoot?',readyAgain:'↻ Check again',readyGo:'● Start recording',
  band:'👁 Reading band (eye contact)',bAll:'All',b1:'1 line',b2:'2 lines',b3:'3 lines',
  eyeRecipe:'👁 Apply eye-contact setup',dist:'📏 Face-to-phone distance (cm)',
  mode:'🎯 Shooting mode',mFree:'Free',mStory:'Story',mPost:'IG Post',mVideo:'YouTube',
  tgSafe:'🚫 Show platform UI zones',
  micLevel:'🎙 Microphone level',fixAudio:'🔊 Repair audio (refresh mic)',
  audTest:'🔎 Audio test (let the device decide)',
  audTestHint:'Tries every recording format and keeps the one that actually writes audio. Takes about 15 seconds.',
  fixAudioHint:'If your takes come out silent, tap this: camera and mic are re-acquired.',
  tgSafeAudio:'🛡 Safe audio mode (recommended on iPhone)',
  safeAudioHint:'Opens the camera with the simplest request (no resolution ask). This is the setting that fixes silent recordings on iPhone.',
  micHint:'Talk — if the bar does not move, no audio is recorded. Check iOS Settings → Safari → Microphone, or close another app holding the mic.',
  noMicShort:'🔇 no microphone — audio is not recorded',
  reopenCam:'🔁 Restart camera',targetDur:'Target duration (pacing)',targetHint:'With a target set, the badge shows if you are ahead or behind.',
  voiceLang:'Voice-follow language',tgLock:'🔒 Lock screen while recording',tgKeepAwake:'☀️ Keep screen awake',tgHideUI:'🫧 Hide buttons while recording',
  resetAll:'↺ Reset settings to defaults',resetHint:'Only settings are reset — your scripts and takes stay.',
  devBtn:'📱 Device compatibility',backup:'Backup / Restore',export:'⬆︎ Export',import:'⬇︎ Import',takes:'🎞 My takes',scripts:'Scripts',
  newScript:'＋ New',paste:'📋 Paste',fromFile:'📄 File',sections:'🔖 Sections — tap to jump',
  title:'Title',text:'📝 Script',
  markHint:'# heading · [note] · *emphasis* · / short pause · // long pause · (2) wait · word{pro-nun} hint',delete:'🗑 Delete',apply:'✓ Apply',
  takesHint:'Takes are kept in this browser\'s storage. Use "Save / Share" to add to Photos.',
  takeReady:'Take ready',deleteRedo:'🗑 Delete',keep:'Close',saveShare:'📤 Share / Save',toFiles:'📁 Save to Files',
  editBtn:'✂️ Edit',trimSteps:'✂️ To trim: <b>Save to Photos</b> first → open it in <b>Photos</b> → <b>Edit</b> → drag the ends of the strip. Trimming there is lossless too.',trimStart:'✂️ Trim start',trimEnd:'✂️ Trim end',
  trimPrev:'▶︎ Play selection',trimGo:'✂️ Cut and apply',
  saveHint:'Tap <b>“Save Video”</b> in the sheet — it goes to Photos. The take is already kept in the app\'s <b>My takes</b> archive.',
  remote:'🎛 Remote control',
  remoteHint:'Bluetooth presenter clicker, page-turner pedal or keyboard — pair it with the phone, press a button, pick what it should do.',
  lastKeyL:'Last key received',learnStart:'🎯 Learn a key',mapReset:'↺ Reset to defaults',mapList:'Key map',
  ssUsed:'Recently used',ssName:'By name',ssLen:'By length',
  csClean:'Clean',csSocial:'Social (big, centred)',capMaxW:'Max words per line',
  profL:'⚡ Quick setup',pfReels:'Reels',pfYT:'YouTube',pfTalk:'Talk',
  profHint:'One tap applies a tested set for that job: pace, aspect, reading band, audio and video filter together. You can still change anything afterwards.',
  vadL:'🫁 Breath flow',tgVad:'Pause the prompter when you stop speaking',vadSens:'Sensitivity',
  tgHicon:'◐ High contrast',newsTitle:'🆕 What changed?',capBtnL:'💬 Caption file',pkgBtnL:'📦 Publish bundle',setFindPh:'🔎 Search settings…',restoreBk:'🛟 Restore auto-backup',vfxTitle:'🎨 Video filter',vfxOff:'Off',vfxNat:'Natural',vfxBright:'Bright',vfxWarm:'Warm',vfxCrisp:'Crisp',vfxLow:'Low light',
  vfxHint:'The filter is baked into the video only while <b>composite is on</b>. Sharpening is kept low in the low-light preset because it amplifies noise.',fxTitle:'🎚 Audio Studio',fxOff:'Off',fxVoice:'Speech',fxNoisy:'Noisy room',fxStudio:'Studio',
  fxGate:'Noise gate',fxPres:'Clarity',fxWarm:'Body',
  fxAdvHint:'Gate: anything below this level (air-con, distant talk, keyboard) is ducked. Too high and your own sentence openings get clipped.',pickKey:'🎯 Sample the screen colour from camera',tgMask:'🎭 Mask preview (removed area in magenta)',bkSoft:'Soft',brL:'Video quality / file size',brLow:'Small file',brMid:'Balanced',brHigh:'Best',micSel:'🎙 Microphone',tgEyeLine:'👁 Eye-line guide (rule of thirds)',
  eyeLineHint:'Keep your eyes on the upper line — the rule used in film and news. Too high leaves headroom; too low crops your chin.',tap1:'Single press',tap2:'Double press',wakeWordL:'Your own trigger word',mapExport:'⬆︎ Export profile',mapImport:'⬇︎ Import profile',
  noRemoteHint:'No clicker? <b>Double-tap the left half</b> to lock, <b>−/+ in the bottom bar</b> for speed, <b>drag</b> to move. 🎤 voice commands do the same job.',tSplit:'🪓 Split long lines',sortNew:'Newest first',sortBig:'Largest first',sortLong:'Longest first',
  wipeTakes:'🗑 Delete unstarred',voiceTest:'🎤 Test mic and recognition',findPh:'🔎 Search scripts…',undoDel:'↺ Restore deleted',
  voiceCmdL:'🗣 Voice commands',voiceCmdT:'"prompter start / stop / faster / slower / rewind / record"',
  voiceCmdHint:'Works while the 🎤 button is on. Commands never leak into the script — only two-word phrases starting with "prompter" count.'}
};

const MSG={
 tr:{noCam:'Kameraya erişilemedi',camHelp:'Ayarlar → Safari → Kamera izni verin, ya da kamerasız modu kullanın.',
  recErr:'Kayıt başlatılamadı',needCam:'Önce kamerayı aç',voiceNo:'Bu tarayıcı sesle takibi desteklemiyor',
  voiceOn:'🎤 Konuşmaya başla — metin seni takip edecek',wipeStuck:'Depo cevap vermiyor, silme yarıda kaldı',takeGone:'Bu çekim artık arşivde yok',wakeMulti:'· TEK kelime olmalı, boşluklu tetik hiçbir zaman tanınmaz',wakeBad:'· Bu tetik harf ya da rakam içermiyor, tanınamaz',vlSet:'🎤 Sesle takip dili',voiceOff:'Sesle takip kapalı',micDenied:'Mikrofon izni gerekli',deleted:'Silindi',copied:'Panodan alındı',clipNo:'Panoya erişilemedi — elle yapıştır',
  end:'Metin bitti',locked:'🔒 Ekran kilitlendi',unlocked:'Kilit açıldı',newVer:'Yeni sürüm hazır — yenile',
  exported:'Yedek indirildi',imported:'Geri yüklendi',impErr:'Dosya okunamadı',noTakes:'Henüz çekim yok',
  tDone:'Metin güncellendi',tUndone:'↺ Geri alındı',toolNoop:'Değişiklik gerekmedi',
  emptyText:'Metin boş',takeKept:'Çekimlerim\'e kaydedildi',mapReset:'Varsayılan eşleme geri geldi',
  noMic:'🔇 Mikrofon yok — video sessiz kaydedilecek. Ayarlar → Kamera\'daki seviye çubuğuna bak.',
  noMicShort:'mikrofon yok',micOk:'ses geliyor ✓',micQuiet:'sessiz — konuş',
  micIosOff:'iPhone\'da kapalı (kaydı sessizleştiriyordu)',audTesting:'Deneniyor… (15 sn)',audTestWin:'✓ Sesli kaydeden biçim bulundu ve seçildi',audTestNone:'⚠️ Hiçbir biçimde ses yazılamadı',micRefresh:'🔊 Mikrofon tazeleniyor…',micFixed:'🔊 Mikrofon yenilendi — tekrar çek',
  audClip:'⚠️ Ses kırpıyor — mikrofondan uzaklaş ya da daha sakin konuş',
  takeFav:'Yıldızla', takeUnfav:'Yıldızı kaldır', takePlay:'Çekimi oynat',
  takeSrt:'Altyazı dosyasını indir', takeShare:'Çekimi paylaş veya kaydet',
  takeDel:'Çekimi sil', scDup:'Senaryoyu çoğalt', mapDel:'Tuş eşlemesini sil',
  pkgDone:'dosya tek pakette hazır', noTake:'Önce bir çekim yap',
  takeNote:'Çekim notu yaz', takeNotePrompt:'Bu çekim için not (neden iyi ya da kötü):',
  verSwitch:'Senaryonun diğer sürümüne geç', verSwitched:'Sürüm', verEmpty:'Önce bu sürüme metin yaz',
  dlgBusy:'⛔ Kayıt sürerken bu pencere açılamaz — sufle ve görüntü donar',
  audClipShort:'ses kırpıyor',audLowShort:'ses kısık',audOkShort:'ses iyi',
  recOn:'KAYITTA',recPaused:'DURAKLADI',recPausedInfo:'⏸ Kayıt duraklatıldı — ⏺ ile aynı videoya devam edersin',
  recResumed:'⏺ Kayıt devam ediyor',pauseNo:'Bu cihazda kayıt duraklatılamıyor',
  resetSure:'Emin misin? Tekrar bas',resetDone:'Ayarlar varsayılana döndü',
  trimNo:'Bu cihaz uygulama içinde kesmeyi desteklemiyor — videoyu Fotoğraflar\'a kaydedip oradan kırp (kalite kaybı da olmaz)',
  notMp4:'Video MP4 değil — Fotoğraflar kabul etmeyebilir',
  shareFail:'Paylaşım açılamadı',
  noFileShare:'Bu tarayıcı dosya paylaşamıyor — Safari\'de aç',
  noShare:'Bu tarayıcıda paylaşım yok — Safari\'de aç',
  rewound:'↺ Metin başa sarıldı',
  toFilesDone:'📁 Dosyalar\'a indi — Dosyalar uygulamasında aç, oradan Fotoğraflar\'a taşıyabilirsin',
  savedFiles:'Dosyalar\'a indirildi → Dosyalar uygulamasında videoyu aç → Paylaş → Videoyu Kaydet',trimShort:'Seçim çok kısa',trimming:'Kesiliyor…',trimDone:'✂️ Kesildi',trimFail:'Kesme başarısız — Fotoğraflar\'da kırpmayı dene',
  audioFallback:'Ham ses açılamadı, normal sese geçildi',
  noCaps:'Altyazı üretilemedi — kayıt sırasında sufle akmamış',capsMade:'altyazı satırı',
  needsComp:'Kompozit açıldı — bu özellik ancak kompozit görüntü üstünde çalışır',
  camDenied:'📷 Kamera izni verilmemiş — ',
  camBusy:'📷 Kamera başka uygulamada açık — FaceTime/Zoom/Kamera\'yı kapat ve tekrar dene',
  camNone:'📷 Uygun kamera bulunamadı — çözünürlüğü 720p yapıp tekrar dene',
  delConfirm:'⚠️ Emin misin? Tekrar bas',deletedUndo:'Silindi — ↺ ile geri getirebilirsin',
  restored:'↺ Senaryo geri geldi',vidDied:'⛔ GÖRÜNTÜ KESİLDİ — ses sürüyor ama video durdu, kaydı bitir',audDied:'⛔ SES KESİLDİ — görüntü sürüyor ama mikrofon gitti, kaydı bitir',fxDead:'⛔ Ses işleme durdu — bundan sonrası SESSİZ kaydediliyor, kaydı bitir',fxBack:'🔊 Ses işleme geri geldi',marksReset:'Metin değişti — bölüm ✓ işaretleri ve zorlanma haritası sıfırlandı',vadOffRec:'🫁 Nefesle akış kayıt boyunca kapatıldı (iPhone sesi korunuyor)',recBusy:'Kayıt sürerken senaryo değiştirilemez — önce kaydı durdur',micGone:'🎙 Seçili mikrofon bulunamadı (çıkarılmış olabilir) — dahili mikrofona dönüldü',noBackup:'Otomatik yedek yok (birkaç düzenleme sonra oluşur)',restoredBackup:'🛟 Yedekten dönüldü —',keyPicked:'Perde rengi ölçüldü →',keyPickFail:'Renk ölçülemedi',longScript:'⚠️ Metin çok uzun — sufle takılabilir, bölümlere ayırmayı düşün',wiped:'yıldızsız çekim silindi',nothingWipe:'Silinecek yıldızsız çekim yok',noMatch:'Eşleşen senaryo yok',mapIn:'🎮 Kumanda profili yüklendi —',mapInBad:'Bu dosya bir kumanda profili değil',mapInEmpty:'Dosyada tanınan tuş eşlemesi yok — profil değişmedi',mapInErr:'Dosya okunamadı',
  jsErr:'⚠️ Bir şey ters gitti — ayrıntı: Ayarlar → Diğer → Cihaz uyumluluğu',
  lsFull:'⚠️ Depo dolu — senaryo KAYDEDİLEMEDİ. Arka plan görselini kaldır ya da kullanmadığın senaryoları sil.',lsFreed:'🧹 Silinen senaryolar kalıcı olarak temizlendi ve senaryon kaydedildi',
  cfgBroken:'⚠️ Ayar dosyası bozuktu, varsayılana dönüldü (bozuk kopya saklandı)',
  archFail:'⚠️ Çekim arşive yazılamadı (depo dolu) — video elinde, hemen paylaş/kaydet',archWarnTxt:'⚠️ Bu çekim arşive yazılamadı — depoda yer yok. Video şu an yalnızca burada: kapatmadan önce paylaş ya da yer açıp tekrar dene.',archWipeBtn:'🗑 Yıldızsız çekimleri sil ve tekrar dene',archWipeSure:'Emin misin? Geri alınamaz —',archRetryOk:'✓ Yer açıldı, çekim arşive yazıldı',archRetryFail:'Hâlâ yazılamadı — videoyu kapatmadan paylaş',archNoWipe:'Silinecek yıldızsız çekim yok — videoyu kapatmadan paylaş',
  recDied:'⛔ Kayıt yarıda kesildi — o ana kadarki bölüm duruyor',
  recNoStart:'⛔ Kayıt başlamadı — kamerayı kapatıp aç, sonra tekrar dene',
  recNoData:'⚠️ Kayıttan veri gelmiyor — durdurup tekrar başlat',
  camBusyRec:'⛔ Kayıt sürerken kamera/mikrofon değiştirilemez — önce kaydı durdur',compBusyRec:'⛔ Kayıt sürerken kompozit açılıp kapatılamaz — kayda giden görüntü çekim başında belirleniyor',nextTakeOnly:'ℹ️ Bu ayar SONRAKİ çekimde geçerli — süren kayda yansımıyor',
  glLostRec:'⛔ Kompozit kayıt sırasında koptu — çekim burada bitirildi, o ana kadarki kısım arşivde',
  glLost:'⚠️ Kompozit koptu (bellek) — kompoziti kapatıp aç',
  glBack:'✅ Kompozit geri geldi',
  camBack:'✅ Kamera yeniden bağlandı',
  voiceDied:'⛔ Sesle takip bağlantısı koptu — 🎤 ile tekrar aç',
  compAudioWarn:'⚠️ iPhone\'da kompozit açıkken ses kaydedilmeyebilir — sesli çekimde kapalı tut',
  compNo:'Bu cihaz/tarayıcı kompozit kaydı desteklemiyor',compFallback:'Kompozit kayıt kurulamadı, ham kamerayla kaydediliyor',
  bgSet:'Arka plan görseli yüklendi',bgCleared:'Arka plan görseli kaldırıldı',
  bgTooBig:'Görsel çok büyük — daha küçük bir görsel seç',bgDosyaBuyuk:'Görsel dosyası çok büyük — 25 MB altında bir görsel seç',tiltOk:'📐 Eğim ölçümü açık',tiltNo:'Bu cihazda eğim ölçülemiyor',resumed:'↩︎ Kaldığın yerden'},
 en:{noCam:'Camera unavailable',camHelp:'Allow camera in Settings → Safari, or use prompter-only mode.',
  recErr:'Could not start recording',needCam:'Open the camera first',voiceNo:'This browser has no speech recognition',
  voiceOn:'🎤 Start talking — the script will follow you',wipeStuck:'Storage is not responding, deletion stopped early',takeGone:'That take is no longer in the archive',wakeMulti:'· Must be ONE word, a trigger with spaces is never recognised',wakeBad:'· This trigger has no letters or digits, so it can never match',vlSet:'🎤 Voice-follow language',voiceOff:'Voice follow off',micDenied:'Microphone permission needed',deleted:'Deleted',copied:'Pasted from clipboard',clipNo:'Clipboard blocked — paste manually',
  end:'End of script',locked:'🔒 Screen locked',unlocked:'Unlocked',newVer:'New version ready — reload',
  exported:'Backup downloaded',imported:'Restored',impErr:'Could not read file',noTakes:'No takes yet',
  tDone:'Script updated',tUndone:'↺ Undone',toolNoop:'Nothing to change',
  emptyText:'Script is empty',takeKept:'Saved to My takes',mapReset:'Default key map restored',
  noMic:'🔇 No microphone — the video will be silent. Check the level bar in Settings → Camera.',
  recOn:'RECORDING',recPaused:'PAUSED',recPausedInfo:'⏸ Paused — press ⏺ to continue the same video',
  recResumed:'⏺ Recording again',pauseNo:'This device cannot pause recording',
  resetSure:'Sure? Press again',resetDone:'Settings reset to defaults',
  trimNo:'This device cannot trim in-app — save to Photos and trim there (lossless too)',
  notMp4:'Not MP4 — Photos may refuse it',
  shareFail:'Could not open the share sheet',
  noFileShare:'This browser cannot share files — open in Safari',
  noShare:'No sharing in this browser — open in Safari',
  rewound:'↺ Rewound to the start',
  toFilesDone:'📁 Saved to Files — open it there to move it into Photos',
  savedFiles:'Downloaded to Files → open it in the Files app → Share → Save Video',trimShort:'Selection too short',trimming:'Cutting…',trimDone:'✂️ Trimmed',trimFail:'Trim failed — try trimming in Photos',
  noMicShort:'no mic',micOk:'audio ✓',micQuiet:'silent — talk',
  micIosOff:'off on iPhone (it was silencing recordings)',audTesting:'Testing… (15s)',audTestWin:'✓ Found a format that records audio',audTestNone:'⚠️ No format produced audio',micRefresh:'🔊 Refreshing microphone…',micFixed:'🔊 Microphone refreshed — record again',
  audClip:'⚠️ Audio is clipping — back off the mic or speak softer',
  takeFav:'Star this take', takeUnfav:'Remove star', takePlay:'Play take',
  takeSrt:'Download subtitle file', takeShare:'Share or save take',
  takeDel:'Delete take', scDup:'Duplicate script', mapDel:'Delete key mapping',
  pkgDone:'files bundled', noTake:'Record a take first',
  takeNote:'Add take note', takeNotePrompt:'Note for this take (why it was good or bad):',
  verSwitch:'Switch to the other script version', verSwitched:'Version', verEmpty:'Write something in this version first',
  dlgBusy:'⛔ Cannot open this dialog while recording — the prompter and video would freeze',
  audClipShort:'clipping',audLowShort:'too quiet',audOkShort:'audio ok',
  audioFallback:'Raw audio unavailable, switched to normal audio',
  noCaps:'No captions — the prompter did not run while recording',capsMade:'caption lines',
  needsComp:'Composite turned on — this feature only works on the composite image',
  camDenied:'📷 Camera permission denied — ',
  camBusy:'📷 Camera is in use by another app — close FaceTime/Zoom/Camera and retry',
  camNone:'📷 No suitable camera — try 720p and retry',
  delConfirm:'⚠️ Sure? Tap again',deletedUndo:'Deleted — restore it with ↺',
  restored:'↺ Script restored',vidDied:'⛔ VIDEO STOPPED — audio continues but video died, end the take',audDied:'⛔ AUDIO STOPPED — video continues but the microphone is gone, end the take',fxDead:'⛔ Audio processing stopped — the rest is being recorded SILENT, end the take',fxBack:'🔊 Audio processing recovered',marksReset:'Script changed — section ✓ marks and struggle map were cleared',vadOffRec:'🫁 Breath flow paused during recording (protects iPhone audio)',recBusy:'Cannot switch scripts while recording — stop the recording first',micGone:'🎙 Selected microphone is gone — switched back to the built-in one',noBackup:'No auto-backup yet (created after a few edits)',restoredBackup:'🛟 Restored from backup —',keyPicked:'Screen colour sampled →',keyPickFail:'Could not sample colour',longScript:'⚠️ Script is very long — the prompter may stutter; consider splitting it',wiped:'unstarred takes deleted',nothingWipe:'No unstarred takes to delete',noMatch:'No matching script',mapIn:'🎮 Remote profile loaded —',mapInBad:'This file is not a remote profile',mapInEmpty:'No usable key mapping in the file — the profile is unchanged',mapInErr:'Could not read the file',
  jsErr:'⚠️ Something went wrong — details in Settings → More → Device compatibility',
  lsFull:'⚠️ Storage full — script was NOT saved. Remove the background image or delete scripts you no longer need.',lsFreed:'🧹 Deleted scripts were purged and your script was saved',
  cfgBroken:'⚠️ Settings file was corrupt, reset to defaults (broken copy kept)',
  archFail:'⚠️ Take could not be archived (storage full) — the video is here, share it now',archWarnTxt:'⚠️ This take could not be archived — storage is full. The video exists only here right now: share it before closing, or free space and retry.',archWipeBtn:'🗑 Delete unstarred takes and retry',archWipeSure:'Are you sure? This cannot be undone —',archRetryOk:'✓ Space freed, take archived',archRetryFail:'Still could not archive — share the video before closing',archNoWipe:'No unstarred takes to delete — share the video before closing',
  recDied:'⛔ Recording stopped early — what was captured is kept',
  recNoStart:'⛔ Recording did not start — close and reopen the camera, then retry',
  recNoData:'⚠️ No data coming from the recorder — stop and start again',
  camBusyRec:'⛔ Cannot change camera or microphone while recording — stop the take first',compBusyRec:'⛔ Cannot switch the composite on or off while recording — the recorded image is fixed when the take starts',nextTakeOnly:'ℹ️ This setting applies to the NEXT take — it does not affect the take in progress',
  glLostRec:'⛔ Composite dropped mid-recording — the take was ended here; everything up to that point is archived',
  glLost:'⚠️ Composite dropped (memory) — turn composite off and on',
  glBack:'✅ Composite restored',
  camBack:'✅ Camera reconnected',
  voiceDied:'⛔ Voice follow lost its connection — turn it on again with 🎤',
  compAudioWarn:'⚠️ iOS may drop audio while composite is on — keep it off for spoken takes',
  compNo:'This device/browser does not support composite recording',compFallback:'Composite recording failed, using the raw camera',
  bgSet:'Background image loaded',bgCleared:'Background image removed',
  bgTooBig:'Image too large — pick a smaller one',bgDosyaBuyuk:'Image file too large — pick one under 25 MB',tiltOk:'📐 Tilt measuring on',tiltNo:'Tilt is not available on this device',resumed:'↩︎ Resumed where you left off'}
};
