/* SUFLE sözlüğü — TEK KAYNAK. İki kabuğa da derle.py gömer.
   Telefondan olduğu gibi alındı; TR/EN paritesi 240/240 ölçülmüştü ve
   taşımada bozulmadığı diff ile kanıtlandı. Mac bugüne dek Türkçeye
   gömülüydü (data-i18n sayısı 0) — İngilizce desteği buradan gelecek.

   I18N = arayüz etiketleri (t() ve data-i18n)
   MSG  = kullanıcıya gösterilen mesajlar (m())
   Yeni anahtar eklerken TR ve EN'e BİRLİKTE ekle; denetim.py parite farkını
   yakalıyor ama eksik çeviri kullanıcıya boş etiket olarak görünür. */

const I18N={
 tr:{lookHere:'buraya bak',tapNote:'▶︎ başlatmak için ekrana dokun · yukarı-aşağı sürükle = konum · − + ile hız (sağ kenardan da sürükleyebilirsin)',
  lockedPill:'🔒 kilitli — iki kez dokun',introP:'Telefonun önünde okurken doğrudan kaydet. Yazı kameranın hemen altında akar; göz teması bozulmaz.',
  startCam:'Kamerayı Aç & Başla',startNoCam:'Kamerasız sadece sufle',help:'Nasıl kullanılır?',install:'📲 Ana ekrana ekle',settings:'Ayarlar',
  tabRead:'Okuma',tabLook:'Görünüm',tabCam:'Kamera',tabMore:'Diğer',speedWpm:'Hız — WPM (dakikada kelime)',
  speedHint:'Doğal konuşma 120–160 WPM. Metnin tahmini süresi aşağıda.',eyeLine:'👁 Okuma çizgisi konumu (kameraya yaklaştır)',
  fontSize:'Yazı boyutu',lineH:'Satır aralığı',margin:'Kenar boşluğu',tgEye:'🎯 Okuma çizgisi',tgDim:'🌗 Odak karartma',
  tgHl:'✨ Kelime vurgusu',tgFade:'🫥 Okunanı soluklaştır',tgPause:'🫁 Paragraf sonunda nefes durağı',tgCount:'⏱ 3-2-1 geri sayım',
  font:'Yazı tipi',fSystem:'Sistem',fSerif:'Serif',fRound:'Yumuşak',fDys:'Disleksi',weight:'Kalınlık',tracking:'Harf aralığı',
  align:'Hizalama',aCenter:'Orta',aLeft:'Sol',
  caseL:'Harf düzeni (yalnız görünüm)',caseNone:'Normal',caseUp:'BÜYÜK',caseLow:'küçük',
  caseHint:'Metni değiştirmez — altyazı ve senaryo olduğu gibi kalır.',
  tClean:'🧹 Temizle',tJoin:'↩︎ Satırları birleştir',tCase:'Aa Cümle düzeni',toolHint:'Araçlar senaryoyu değiştirir — ↺ ile geri alınır. Cümle düzeni özel isimleri de küçültür, onları elle düzelt.',
  tBreath:'🫁 Nefes işareti',tNum:'🔢 Sayıları yaz',tUndo:'↺ Geri al',textColor:'Yazı rengi',cWhite:'Beyaz',cYellow:'Sarı',cGreen:'Yeşil',cBlack:'Siyah',
  cNavy:'Lacivert',bgColor:'Zemin (kamerasız modda)',scrim:'Kamera üstü karartma (okunurluk)',
  tgMirror:'🪞 Yazıyı aynala (cam rig / beam splitter)',tgFlip:'🔃 Yazıyı dikey çevir',tgShadow:'🌑 Yazı gölgesi',
  quality:'Kayıt kalitesi',qHint:'Cihaz desteklemezse en yakın çözünürlüğe düşer.',frameGuide:'Çerçeve kılavuzu',aspNone:'Kapalı',
  zoom:'Yakınlaştırma',tgBack:'🔄 Arka kamera',tgTorch:'🔦 Işık (fener)',tgGrid:'▦ Üçler kuralı + baş boşluğu',
  tgRaw:'🎚 Ham ses (hiç işleme yapma)',
  rawHint:'Ham ses daha doğal tınlar ama bazı iPhone\'larda sorun çıkarır — ses gelmiyorsa kapalı bırakın.',
  lightTitle:'💡 Işık ve çerçeve denetçisi',lightBtn:'🔎 Şimdi denetle',tiltBtn:'📐 Eğim ölç',
  lightHint:'Bu sekme açıkken saniyede bir ölçüyor. Yüz bölgesinin parlaklığını kenarlarla karşılaştırıp arkadan ışığı, patlamayı ve kontrast eksikliğini yakalar.',
  compTitle:'🎛 Kompozit kayıt (gerçek kırpma + yeşil ekran)',tgComp:'Kompoziti aç',
  compHint:'Kayıt kameradan değil işlenmiş tuvalden alınır: seçtiğin oran gerçekten kırpılır ve yeşil ekran çalışır. Pil/ısı maliyeti vardır, gerekmedikçe kapalı tut.',
  tgBurn:'💬 Altyazıyı videoya göm',capSize:'Altyazı boyutu',capPos:'Altyazı konumu',cpBottom:'Alt',cpMiddle:'Orta',
  burnHint:'Okuduğun cümle videonun üstüne yazılır — ayrı altyazı dosyası yüklemene gerek kalmaz. Kompozit açık olmalı.',
  tgChroma:'🟩 Yeşil ekran (chroma key)',keyColor:'Perde rengi',kGreen:'Yeşil',kBlue:'Mavi',kCream:'Krem',
  keySim:'Eşik (ne kadarı silinsin)',keySmooth:'Kenar yumuşaklığı',newBg:'Yeni arka plan',
  spill:'Saçak temizliği (despill)',bkColor:'Düz renk',bkStudio:'Stüdyo',bkWarm:'Sıcak',bkCool:'Soğuk',
  bkBokeh:'Bokeh',bkBrand:'Marka',bkImage:'Görsel',
  bgPick:'🖼 Görsel seç',bgClear:'✕ Görseli kaldır',
  chromaHint:'Yeşil ekran olmadan arka plan değiştirilemez — kişiyi arka plandan ayırmak için yapay zekâ modeli gerekir, o telefonda çok ağır. Düz renkli bir perde/duvar yeter (kırışıksız ve eşit aydınlatılmış olsun).',
  capOffset:'💬 Altyazı kayması (sn)',
  capHint:'Altyazı senaryodan üretilir, konuşma tanıma kullanılmaz — yazım her zaman doğrudur. Zamanlama kelimenin okuma çizgisinden geçtiği andır; erken/geç çıkıyorsa buradan kaydır.',
  tgBionic:'⚡ Biyonik okuma (kelime başları kalın)',
  tgSection:'🎬 Bölüm sonunda dur (bölüm bölüm çek)',
  secHint:'Açıkken sufle her # bölümünün sonunda durur; o bölümü çekip kaydı kapatınca bölüm ✓ işaretlenir. Senaryolar sayfasında hangi bölümü çektiğini görürsün.',checkBtn:'🔍 Konuşulabilirlik denetimi',diffBtn:'🗺 Zorlanma haritası',
  spLabel:'HIZ · WPM',readyTitle:'✅ Çekime hazır mıyım?',readyAgain:'↻ Tekrar bak',readyGo:'● Çekime başla',
  band:'👁 Okuma şeridi (göz teması)',bAll:'Tümü',b1:'1 satır',b2:'2 satır',b3:'3 satır',
  eyeRecipe:'👁 Göz teması ayarını uygula',dist:'📏 Yüz–telefon mesafesi (cm)',
  mode:'🎯 Çekim modu',mFree:'Serbest',mStory:'Story',mPost:'IG Gönderi',mVideo:'YouTube',
  tgSafe:'🚫 Platform arayüz alanlarını göster',
  micLevel:'🎙 Mikrofon seviyesi',fixAudio:'🔊 Sesi onar (mikrofonu tazele)',
  audTest:'🔎 Ses testi (cihaza yaptır)',
  audTestHint:'Telefonun hangi kayıt biçiminde ses yazdığını tek tek dener ve çalışanı kalıcı seçer. Yaklaşık 15 saniye sürer.',
  fixAudioHint:'Çekimde ses çıkmıyorsa buna bas: kamera ve mikrofon sıfırdan açılır.',
  tgSafeAudio:'🛡 Güvenli ses modu (iPhone için önerilir)',
  safeAudioHint:'Kamerayı en sade ayarlarla açar (çözünürlük isteği yok). iPhone\'da sessiz kayıt sorununu çözen ayar budur; kapatırsan yüksek çözünürlük istenir.',
  micHint:'Konuş — çubuk oynamıyorsa ses kaydedilmez. Oynamıyorsa: iOS Ayarlar → Safari → Mikrofon izni, ya da mikrofonu tutan başka bir uygulamayı kapat.',
  noMicShort:'🔇 mikrofon yok — ses kaydedilmiyor',
  reopenCam:'🔁 Kamerayı yeniden başlat',targetDur:'Hedef süre (pacing)',targetHint:'Hedef verirsen üstteki rozet geri/ileri olduğunu gösterir.',
  voiceLang:'Sesle takip dili',tgLock:'🔒 Kayıtta ekranı kilitle',tgKeepAwake:'☀️ Ekranı uyanık tut',tgHideUI:'🫧 Kayıtta düğmeleri gizle',
  resetAll:'↺ Ayarları varsayılana döndür',resetHint:'Yalnız ayarları sıfırlar — senaryoların ve çekimlerin durur.',
  devBtn:'📱 Cihaz uyumluluğu',backup:'Yedekle / Geri yükle',export:'⬆︎ Dışa aktar',import:'⬇︎ İçe aktar',takes:'🎞 Çekimlerim',scripts:'Senaryolar',
  newScript:'＋ Yeni',paste:'📋 Yapıştır',fromFile:'📄 Dosya',sections:'🔖 Bölümler — dokun, oraya atla',
  title:'Başlık',text:'📝 Metin',
  markHint:'# başlık · [not] · *vurgu* · / kısa dur · // uzun dur · (2) bekle · kelime{o-ku-nuş} telaffuz',delete:'🗑 Sil',apply:'✓ Uygula',
  takesHint:'Çekimler telefonun tarayıcı deposunda tutulur. Fotoğraflar\'a eklemek için "Kaydet / Paylaş"a bas.',
  takeReady:'Çekim hazır',deleteRedo:'🗑 Sil',keep:'Kapat',saveShare:'📤 Paylaş / Kaydet',toFiles:"📁 Dosyalar'a Kaydet",
  editBtn:'✂️ Düzenle',trimSteps:'✂️ Kırpmak istersen: önce <b>Fotoğraflara Kaydet</b> → <b>Fotoğraflar</b> uygulamasında videoyu aç → sağ üstten <b>Düzenle</b> → alttaki şeridin uçlarından çek. Orada kırpmak kalite kaybı da yapmaz.',trimStart:'✂️ Baştan kes',trimEnd:'✂️ Sondan kes',
  trimPrev:'▶︎ Seçimi oynat',trimGo:'✂️ Kes ve uygula',
  saveHint:'Açılan menüde <b>“Videoyu Kaydet”</b>e dokun — video Fotoğraflar\'a gider. Çekim zaten uygulamanın <b>Çekimlerim</b> arşivinde duruyor, oradan da ulaşabilirsin.',
  remote:'🎛 Uzaktan kumanda',
  remoteHint:'Bluetooth sunum kumandası, sayfa çevirici pedal veya klavye — telefonla eşleştir, aşağıdaki tuşa bas, ne yapacağını seç.',
  lastKeyL:'Gelen son tuş',learnStart:'🎯 Tuş öğret',mapReset:'↺ Varsayılana dön',mapList:'Eşleme tablosu',
  ssUsed:'Son kullanılan',ssName:'Ada göre',ssLen:'Uzunluğa göre',
  csClean:'Sade',csSocial:'Sosyal (büyük, ortada)',capMaxW:'Satırda en fazla kelime',
  profL:'⚡ Hazır kurulum',pfReels:'Reels',pfYT:'YouTube',pfTalk:'Sunum',
  profHint:'Tek dokunuşla o iş için denenmiş ayar takımı: hız, oran, okuma şeridi, ses ve görüntü filtresi birlikte ayarlanır. Sonrasında istediğini değiştirebilirsin.',
  vadL:'🫁 Nefesle akış',tgVad:'Konuşmayı kesince sufle dursun',vadSens:'Duyarlılık',
  tgHicon:'◐ Yüksek kontrast',newsTitle:'🆕 Ne değişti?',capBtnL:'💬 Altyazı dosyası',pkgBtnL:'📦 Yayın paketi',setFindPh:'🔎 Ayarlarda ara…',restoreBk:'🛟 Otomatik yedekten dön',vfxTitle:'🎨 Görüntü filtresi',vfxOff:'Kapalı',vfxNat:'Doğal',vfxBright:'Aydınlık',vfxWarm:'Sıcak',vfxCrisp:'Net',vfxLow:'Az ışık',
  vfxHint:'Filtre yalnız <b>kompozit açıkken</b> videoya işlenir — kompozit kapalıysa görüntü ham kaydedilir. Az ışıkta keskinlik gürültüyü büyüttüğü için o hazır ayarda kasten düşük tutuldu.',fxTitle:'🎚 Ses Stüdyosu',fxOff:'Kapalı',fxVoice:'Konuşma',fxNoisy:'Gürültülü ortam',fxStudio:'Stüdyo',
  fxGate:'Gürültü kapısı',fxPres:'Netlik (anlaşılırlık)',fxWarm:'Tok ses (gövde)',
  fxAdvHint:'Kapı: bu eşiğin altındaki sesler (klima, uzaktaki konuşma, klavye) kısılır. Çok yüksek tutarsan kendi cümle başların da kesilir.',pickKey:'🎯 Perdenin rengini kameradan ölç',tgMask:'🎭 Maske önizlemesi (silinen yer mor)',bkSoft:'Yumuşak',brL:'Video kalitesi / dosya boyutu',brLow:'Küçük dosya',brMid:'Dengeli',brHigh:'En iyi',micSel:'🎙 Mikrofon',tgEyeLine:'👁 Göz hattı kılavuzu (üçte bir)',
  eyeLineHint:'Gözlerin üstteki çizgide olsun — sinemada ve haberde kullanılan kural. Çok yukarıdaysan kafanın üstünde boşluk kalır, çok aşağıdaysan çene kesilir.',tap1:'Tek basış',tap2:'Çift basış',wakeWordL:'Kendi tetik kelimen',mapExport:'⬆︎ Profili dışa aktar',mapImport:'⬇︎ Profili içe aktar',
  noRemoteHint:'Kumandan yok mu? Ekranın <b>sol yarısına</b> çift dokunuş kilit, <b>alt şeritteki −/+</b> hız, <b>parmakla sürükleme</b> konum içindir. 🎤 sesli komut da aynı işi görür.',tSplit:'🪓 Uzun satırları böl',sortNew:'Yeni önce',sortBig:'Büyük önce',sortLong:'Uzun önce',
  wipeTakes:'🗑 Yıldızsızları sil',voiceTest:'🎤 Mikrofonu ve tanımayı sına',findPh:'🔎 Senaryolarda ara…',undoDel:'↺ Silineni geri getir',
  voiceCmdL:'🗣 Sesli komut',voiceCmdT:'"sufle başla / dur / hızlan / yavaşla / başa dön / kaydet"',
  voiceCmdHint:'🎤 düğmesi açıkken çalışır. Komutlar metne karışmaz — "sufle" ile başlayan iki kelimelik kalıplar komut sayılır.',
  /* --- Mac kabuğu (A.2b) --- */
  mFmt916:'📱 9:16',mFmt169:'🖥 16:9',mFmt11:'⬜ 1:1',mFmt45:'📷 4:5',mFmtFull:'⛶ Tam',mReady:'✅ Hazır mıyım',mUndoDel:'↺ Geri getir',mPip:'🪟 Yüzen Sufle',mFullscreen:'⛶ Tam Ekran',mSections:'🔖 Bölümler',mShorts:'Shorts',mNoisy:'Gürültülü',mThreshold:'Eşik',mDarkGreen:'Koyu yeşil',mRemove:'✕ Kaldır',mEyeLine:'👁 Okuma Çizgisi (kameraya yaklaştır)',mFaceDist:'📏 Yüz–ekran mesafesi (cm)',mScreenH:'🖥 Ekran yüksekliği (cm)',mCaseView:'Aa Harf düzeni (yalnız görünüm)',mMono:'Mono',mTheme:'Tema',mCustomFg:'Özel: Yazı / Zemin',mRemoteCtrl:'📲 Telefon Uzaktan Kumanda',mDiscard:'🗑 Sil / Yeniden',mCaptions:'💬 Altyazı',mPubNote:'📝 Yayın notu',mKeep:'⭐ Arşive al',
  /* Mac'in BİREBİR metinleri. Telefonla sözcük farkı var (emoji öneki,
     büyük harf); birleştirmek görünür bir UI kararıdır ve FAZ B'ye ait,
     sözlük göçünün yan etkisi olamaz. O yüzden ayrı anahtar. */
  mScripts:'⬆︎ Senaryolar',mCsClean:'⇔ Sade',mBkImage:'🖼 Görsel',mCapMaxW:'💬 Satırda en fazla kelime',mFontSize:'Yazı Boyutu',mLineH:'Satır Aralığı',mMargin:'Kenar Boşluğu',mFont:'Yazı Tipi',
  /* Mac öznitelik metinleri (A.2c): title / placeholder / aria-label */
  mTReset:'Başa sar (R)',mTFmt:'Çekim formatı',mTVoice:'Konuştukça kayan sufle',mTReady:'Çekime hazır mıyım?',mTUndoDel:'Son silinen senaryoyu geri getir',mTPip:'Zoom/Teams görüşmesinde ya da başka uygulama üstünde okumak için',mTTakes:'Arşivdeki çekimler',mTExport:'Senaryoları dosyaya aktar (telefona taşımak için)',mTFs:'Tam ekran (F)',mTHide:'Panelleri gizle (H)',mTNew:'Yeni senaryo',mTNews:'🆕 Ne değişti? — sürüm notları',mANews:'Ne değişti? Sürüm notları',mTErrDetail:'Ayrıntı için tıkla',mThClassic:'Klasik',mThWhite:'Beyaz',mThGreen:'Yeşil',mThBlue:'Mavi',mThAmber:'Amber',mPhTitle:'Senaryo başlığı',mPhEditor:'Okuyacağınız metni buraya yazın veya yapıştırın...',
  /* Mac anahtar etiketleri + durum çubuğu (A.2d) */
  mSwCrop:'⧉ Seçilen orana kırparak kaydet',mSwChroma:'🟩 Yeşil ekran (chroma key)',mSwBurn:'💬 Altyazıyı videoya göm',mSwVad:'🫁 Konuşmayı kesince sufle dursun',mSwSafe:'🚫 Platform arayüz alanları',mSwBionic:'⚡ Biyonik okuma (kelime başları kalın)',mSwMirror:'🪞 Ayna (yatay çevir)',mSwFlip:'🔃 Ters (dikey çevir)',mSwEye:'🎯 Göz çizgisi',mSwDim:'🌗 Odak karartma',mSwHl:'✨ Kelime vurgusu',mSwCount:'⏱ 3-2-1 sayaç',mSbPlay:'<kbd>Boşluk</kbd> başlat',mSbSpeed:'<kbd>↑</kbd><kbd>↓</kbd> hız',mSbReset:'<kbd>R</kbd> başa',mSbLine:'<kbd>←</kbd><kbd>→</kbd> satır',mSbRec:'<kbd>K</kbd> kayıt',mSbFs:'<kbd>F</kbd> tam ekran',mSbHide:'<kbd>H</kbd> sade',
  /* Mac ipucu ve panel metinleri (A.2d) */
  mHScripts:'Senaryolar',mNoteAudio:'Uğultu kesme + 50 Hz şebeke çentiği + gürültü kapısı + seviye dengeleme. Dahili mikrofonla çekimde en çok işe yarayan ayar.',mNoteChroma:'Yeşil ekran olmadan arka plan değiştirilemez. Düz renkli, kırışıksız ve eşit aydınlatılmış bir perde yeter. Kırparak kayıt açık olmalı.',mNoteCase:'Metni değiştirmez — altyazı ve senaryo olduğu gibi kalır.',mNoteBionic:'Gözün kelimeyi baştan yakalamasını kolaylaştırır. Yalnız görünümü değiştirir; altyazı ve .srt etkilenmez.',mNoteCap:'Altyazı senaryodan üretilir, yazım her zaman doğrudur. Erken/geç çıkıyorsa buradan kaydır.',mNoteCapW:'Telefondaki ayarın aynısı. Küçük değer sosyal video için daha okunur, büyük değer daha az satır demek.',mNoteQr:'Telefonla QR’ı okutun ya da şu adrese girin:',mRemoteOff:'📴 <b>Kumanda kapalı.</b> HTML dosyasına çift tıklayarak açtıysan kumanda <b>hiç çalışmaz</b> — tarayıcı file:// modunda sunucuya bağlanamaz.<br>Aynı klasördeki <b>“Teleprompter Sunucu.command”</b> dosyasına çift tıkla; pencere kendiliğinden yeniden açılır ve QR burada belirir.',mRrNote:'Önbellekte tutuluyor — beğenmezsen sil, diske kaydolmaz. İndir\'e basınca kaydedilir. <b>Arşive al</b> dersen tarayıcı deposunda kalır, sonra da açabilirsin.',mRrHead:'🎬 Çekim hazır',
  /* Dil düğmesi (A.2d) */
  mLangLabel:'Arayüz dili',
  /* Mac panel sekmesi (B.3) */
  mTabShoot:'Çekim',
  /* Durum satırı — hangi moddayım (B.5) */
  modeVoice:'🎤 Sesle',modeAuto:'▶︎ Otomatik',modeManual:'✋ Elle',
  /* Kısayol kartı (B.6) */
  keysTitle:'Klavye kısayolları'},
 en:{lookHere:'look here',tapNote:'▶︎ tap to start · drag up/down = position · − + for speed (or drag the right edge)',
  lockedPill:'🔒 locked — double tap',introP:'Record straight from your phone while you read. Text scrolls right under the lens so eye contact holds.',
  startCam:'Open Camera & Start',startNoCam:'Prompter only (no camera)',help:'How to use',install:'📲 Add to home screen',settings:'Settings',
  tabRead:'Reading',tabLook:'Look',tabCam:'Camera',tabMore:'More',speedWpm:'Speed — WPM (words per minute)',
  speedHint:'Natural speech is 120–160 WPM. Estimated duration below.',eyeLine:'👁 Reading line position (closer to lens)',
  fontSize:'Font size',lineH:'Line height',margin:'Side margin',tgEye:'🎯 Reading line',tgDim:'🌗 Focus dimming',
  tgHl:'✨ Word highlight',tgFade:'🫥 Fade read words',tgPause:'🫁 Breath pause at paragraphs',tgCount:'⏱ 3-2-1 countdown',
  font:'Typeface',fSystem:'System',fSerif:'Serif',fRound:'Rounded',fDys:'Dyslexia',weight:'Weight',tracking:'Letter spacing',
  align:'Alignment',aCenter:'Center',aLeft:'Left',
  caseL:'Letter case (display only)',caseNone:'Normal',caseUp:'UPPER',caseLow:'lower',
  caseHint:'Does not change the script — captions stay as written.',
  tClean:'🧹 Clean up',tJoin:'↩︎ Join lines',tCase:'Aa Sentence case',toolHint:'Tools rewrite the script — ↺ undoes the last one. Sentence case also lowercases proper nouns; fix those by hand.',
  tBreath:'🫁 Breath marks',tNum:'🔢 Numbers to words',tUndo:'↺ Undo',textColor:'Text color',cWhite:'White',cYellow:'Yellow',cGreen:'Green',cBlack:'Black',
  cNavy:'Navy',bgColor:'Background (no-camera mode)',scrim:'Dim over camera (legibility)',
  tgMirror:'🪞 Mirror text (beam splitter rig)',tgFlip:'🔃 Flip text vertically',tgShadow:'🌑 Text shadow',
  quality:'Recording quality',qHint:'Falls back to the closest resolution the device supports.',frameGuide:'Frame guide',aspNone:'Off',
  zoom:'Zoom',tgBack:'🔄 Rear camera',tgTorch:'🔦 Torch',tgGrid:'▦ Rule of thirds + headroom',
  tgRaw:'🎚 Raw audio (no noise suppression)',
  rawHint:'Raw sounds more natural but breaks on some iPhones — leave it off if you get no sound.',
  lightTitle:'💡 Light & framing inspector',lightBtn:'🔎 Check now',tiltBtn:'📐 Measure tilt',
  lightHint:'Samples once per second while this tab is open. Compares face-area brightness with the edges to catch backlight, blown highlights and low contrast.',
  compTitle:'🎛 Composite recording (real crop + green screen)',tgComp:'Enable composite',
  compHint:'Recording comes from a processed canvas instead of the raw camera: your chosen ratio is truly cropped and green screen works. Costs battery/heat — leave it off unless needed.',
  tgBurn:'💬 Burn captions into the video',capSize:'Caption size',capPos:'Caption position',cpBottom:'Bottom',cpMiddle:'Middle',
  burnHint:'The sentence you are reading is drawn on the video — no separate subtitle file needed. Composite must be on.',
  tgChroma:'🟩 Green screen (chroma key)',keyColor:'Screen colour',kGreen:'Green',kBlue:'Blue',kCream:'Cream',
  keySim:'Threshold (how much is removed)',keySmooth:'Edge softness',newBg:'New background',
  spill:'Spill suppression',bkColor:'Solid',bkStudio:'Studio',bkWarm:'Warm',bkCool:'Cool',
  bkBokeh:'Bokeh',bkBrand:'Brand',bkImage:'Image',
  bgPick:'🖼 Pick image',bgClear:'✕ Remove image',
  chromaHint:'Without a green screen the background cannot be replaced — separating a person from the background needs an AI model, which is far too heavy on a phone. A plain, evenly lit sheet or wall is enough.',
  capOffset:'💬 Caption offset (s)',
  capHint:'Captions come from the script, not speech recognition — spelling is always right. Timing is when each word crossed the reading line; shift it here if they appear early or late.',
  tgBionic:'⚡ Bionic reading (bold word starts)',
  tgSection:'🎬 Stop at section end (shoot section by section)',
  secHint:'The prompter stops at the end of every # section; finish that take and the section gets a ✓. The Scripts sheet shows what you have shot.',checkBtn:'🔍 Speakability check',diffBtn:'🗺 Struggle map',
  spLabel:'SPEED · WPM',readyTitle:'✅ Am I ready to shoot?',readyAgain:'↻ Check again',readyGo:'● Start recording',
  band:'👁 Reading band (eye contact)',bAll:'All',b1:'1 line',b2:'2 lines',b3:'3 lines',
  eyeRecipe:'👁 Apply eye-contact setup',dist:'📏 Face-to-phone distance (cm)',
  mode:'🎯 Shooting mode',mFree:'Free',mStory:'Story',mPost:'IG Post',mVideo:'YouTube',
  tgSafe:'🚫 Show platform UI zones',
  micLevel:'🎙 Microphone level',fixAudio:'🔊 Repair audio (refresh mic)',
  audTest:'🔎 Audio test (let the device decide)',
  audTestHint:'Tries every recording format and keeps the one that actually writes audio. Takes about 15 seconds.',
  fixAudioHint:'If your takes come out silent, tap this: camera and mic are re-acquired.',
  tgSafeAudio:'🛡 Safe audio mode (recommended on iPhone)',
  safeAudioHint:'Opens the camera with the simplest request (no resolution ask). This is the setting that fixes silent recordings on iPhone.',
  micHint:'Talk — if the bar does not move, no audio is recorded. Check iOS Settings → Safari → Microphone, or close another app holding the mic.',
  noMicShort:'🔇 no microphone — audio is not recorded',
  reopenCam:'🔁 Restart camera',targetDur:'Target duration (pacing)',targetHint:'With a target set, the badge shows if you are ahead or behind.',
  voiceLang:'Voice-follow language',tgLock:'🔒 Lock screen while recording',tgKeepAwake:'☀️ Keep screen awake',tgHideUI:'🫧 Hide buttons while recording',
  resetAll:'↺ Reset settings to defaults',resetHint:'Only settings are reset — your scripts and takes stay.',
  devBtn:'📱 Device compatibility',backup:'Backup / Restore',export:'⬆︎ Export',import:'⬇︎ Import',takes:'🎞 My takes',scripts:'Scripts',
  newScript:'＋ New',paste:'📋 Paste',fromFile:'📄 File',sections:'🔖 Sections — tap to jump',
  title:'Title',text:'📝 Script',
  markHint:'# heading · [note] · *emphasis* · / short pause · // long pause · (2) wait · word{pro-nun} hint',delete:'🗑 Delete',apply:'✓ Apply',
  takesHint:'Takes are kept in this browser\'s storage. Use "Save / Share" to add to Photos.',
  takeReady:'Take ready',deleteRedo:'🗑 Delete',keep:'Close',saveShare:'📤 Share / Save',toFiles:'📁 Save to Files',
  editBtn:'✂️ Edit',trimSteps:'✂️ To trim: <b>Save to Photos</b> first → open it in <b>Photos</b> → <b>Edit</b> → drag the ends of the strip. Trimming there is lossless too.',trimStart:'✂️ Trim start',trimEnd:'✂️ Trim end',
  trimPrev:'▶︎ Play selection',trimGo:'✂️ Cut and apply',
  saveHint:'Tap <b>“Save Video”</b> in the sheet — it goes to Photos. The take is already kept in the app\'s <b>My takes</b> archive.',
  remote:'🎛 Remote control',
  remoteHint:'Bluetooth presenter clicker, page-turner pedal or keyboard — pair it with the phone, press a button, pick what it should do.',
  lastKeyL:'Last key received',learnStart:'🎯 Learn a key',mapReset:'↺ Reset to defaults',mapList:'Key map',
  ssUsed:'Recently used',ssName:'By name',ssLen:'By length',
  csClean:'Clean',csSocial:'Social (big, centred)',capMaxW:'Max words per line',
  profL:'⚡ Quick setup',pfReels:'Reels',pfYT:'YouTube',pfTalk:'Talk',
  profHint:'One tap applies a tested set for that job: pace, aspect, reading band, audio and video filter together. You can still change anything afterwards.',
  vadL:'🫁 Breath flow',tgVad:'Pause the prompter when you stop speaking',vadSens:'Sensitivity',
  tgHicon:'◐ High contrast',newsTitle:'🆕 What changed?',capBtnL:'💬 Caption file',pkgBtnL:'📦 Publish bundle',setFindPh:'🔎 Search settings…',restoreBk:'🛟 Restore auto-backup',vfxTitle:'🎨 Video filter',vfxOff:'Off',vfxNat:'Natural',vfxBright:'Bright',vfxWarm:'Warm',vfxCrisp:'Crisp',vfxLow:'Low light',
  vfxHint:'The filter is baked into the video only while <b>composite is on</b>. Sharpening is kept low in the low-light preset because it amplifies noise.',fxTitle:'🎚 Audio Studio',fxOff:'Off',fxVoice:'Speech',fxNoisy:'Noisy room',fxStudio:'Studio',
  fxGate:'Noise gate',fxPres:'Clarity',fxWarm:'Body',
  fxAdvHint:'Gate: anything below this level (air-con, distant talk, keyboard) is ducked. Too high and your own sentence openings get clipped.',pickKey:'🎯 Sample the screen colour from camera',tgMask:'🎭 Mask preview (removed area in magenta)',bkSoft:'Soft',brL:'Video quality / file size',brLow:'Small file',brMid:'Balanced',brHigh:'Best',micSel:'🎙 Microphone',tgEyeLine:'👁 Eye-line guide (rule of thirds)',
  eyeLineHint:'Keep your eyes on the upper line — the rule used in film and news. Too high leaves headroom; too low crops your chin.',tap1:'Single press',tap2:'Double press',wakeWordL:'Your own trigger word',mapExport:'⬆︎ Export profile',mapImport:'⬇︎ Import profile',
  noRemoteHint:'No clicker? <b>Double-tap the left half</b> to lock, <b>−/+ in the bottom bar</b> for speed, <b>drag</b> to move. 🎤 voice commands do the same job.',tSplit:'🪓 Split long lines',sortNew:'Newest first',sortBig:'Largest first',sortLong:'Longest first',
  wipeTakes:'🗑 Delete unstarred',voiceTest:'🎤 Test mic and recognition',findPh:'🔎 Search scripts…',undoDel:'↺ Restore deleted',
  voiceCmdL:'🗣 Voice commands',voiceCmdT:'"prompter start / stop / faster / slower / rewind / record"',
  voiceCmdHint:'Works while the 🎤 button is on. Commands never leak into the script — only two-word phrases starting with "prompter" count.',
  /* --- Mac kabuğu (A.2b) --- */
  mFmt916:'📱 9:16',mFmt169:'🖥 16:9',mFmt11:'⬜ 1:1',mFmt45:'📷 4:5',mFmtFull:'⛶ Full',mReady:'✅ Ready?',mUndoDel:'↺ Restore deleted',mPip:'🪟 Floating prompter',mFullscreen:'⛶ Full screen',mSections:'🔖 Sections',mShorts:'Shorts',mNoisy:'Noisy',mThreshold:'Threshold',mDarkGreen:'Dark green',mRemove:'✕ Remove',mEyeLine:'👁 Reading line (closer to the camera)',mFaceDist:'📏 Face-to-screen distance (cm)',mScreenH:'🖥 Screen height (cm)',mCaseView:'Aa Letter case (display only)',mMono:'Mono',mTheme:'Theme',mCustomFg:'Custom: text / background',mRemoteCtrl:'📲 Phone remote control',mDiscard:'🗑 Discard / redo',mCaptions:'💬 Subtitles',mPubNote:'📝 Publish note',mKeep:'⭐ Keep in archive',
  /* Mac'in BİREBİR metinleri. Telefonla sözcük farkı var (emoji öneki,
     büyük harf); birleştirmek görünür bir UI kararıdır ve FAZ B'ye ait,
     sözlük göçünün yan etkisi olamaz. O yüzden ayrı anahtar. */
  mScripts:'⬆︎ Scripts',mCsClean:'⇔ Plain',mBkImage:'🖼 Image',mCapMaxW:'💬 Max words per line',mFontSize:'Font size',mLineH:'Line height',mMargin:'Side margin',mFont:'Typeface',
  /* Mac öznitelik metinleri (A.2c): title / placeholder / aria-label */
  mTReset:'Rewind (R)',mTFmt:'Shooting format',mTVoice:'Prompter that follows your voice',mTReady:'Am I ready to shoot?',mTUndoDel:'Restore the last deleted script',mTPip:'For reading over a Zoom/Teams call or any other app',mTTakes:'Takes in the archive',mTExport:'Export scripts to a file (to move them to your phone)',mTFs:'Full screen (F)',mTHide:'Hide the panels (H)',mTNew:'New script',mTNews:'🆕 What changed? — release notes',mANews:'What changed? Release notes',mTErrDetail:'Click for details',mThClassic:'Classic',mThWhite:'White',mThGreen:'Green',mThBlue:'Blue',mThAmber:'Amber',mPhTitle:'Script title',mPhEditor:'Type or paste the text you will read here...',
  /* Mac anahtar etiketleri + durum çubuğu (A.2d) */
  mSwCrop:'⧉ Record cropped to the chosen ratio',mSwChroma:'🟩 Green screen (chroma key)',mSwBurn:'💬 Burn subtitles into the video',mSwVad:'🫁 Pause the prompter when you stop speaking',mSwSafe:'🚫 Platform interface areas',mSwBionic:'⚡ Bionic reading (bold word beginnings)',mSwMirror:'🪞 Mirror (flip horizontally)',mSwFlip:'🔃 Invert (flip vertically)',mSwEye:'🎯 Eye line',mSwDim:'🌗 Focus dimming',mSwHl:'✨ Word highlight',mSwCount:'⏱ 3-2-1 countdown',mSbPlay:'<kbd>Space</kbd> start',mSbSpeed:'<kbd>↑</kbd><kbd>↓</kbd> speed',mSbReset:'<kbd>R</kbd> rewind',mSbLine:'<kbd>←</kbd><kbd>→</kbd> line',mSbRec:'<kbd>K</kbd> record',mSbFs:'<kbd>F</kbd> full screen',mSbHide:'<kbd>H</kbd> minimal',
  /* Mac ipucu ve panel metinleri (A.2d) */
  mHScripts:'Scripts',mNoteAudio:'Hum removal + 50 Hz mains notch + noise gate + level balancing. Recommended with the built-in microphone.',mNoteChroma:'The background cannot be replaced without a green screen. A plain, wrinkle-free and evenly lit surface works best.',mNoteCase:'Does not change the text — subtitles and the script stay exactly as written.',mNoteBionic:'Helps the eye catch each word from its beginning. Display only; subtitles and the script are untouched.',mNoteCap:'Subtitles are generated from the script, so the spelling is always right. If they run early or late, shift them here.',mNoteCapW:'Same setting as on the phone. A smaller value reads better for social video, a larger one shows more at once.',mNoteQr:'Scan the QR with your phone, or open this address:',mRemoteOff:'📴 <b>Remote is off.</b> If you opened the HTML file by double-clicking it, the remote <b>will not work at all</b> — in file:// mode the browser cannot reach the server. Double-click <b>“Teleprompter Sunucu.command”</b> in the same folder; the window reopens by itself and the QR appears here.',mRrNote:'Held in the cache — delete it if you do not like it, nothing is written to disk. It is saved when you press Download. Choose <b>Keep in archive</b> and it stays in the browser store, so you can open it later.',mRrHead:'🎬 Take ready',
  /* Dil düğmesi (A.2d) */
  mLangLabel:'Interface language',
  /* Mac panel sekmesi (B.3) */
  mTabShoot:'Shooting',
  /* Durum satırı — hangi moddayım (B.5) */
  modeVoice:'🎤 Voice',modeAuto:'▶︎ Auto',modeManual:'✋ Manual',
  /* Kısayol kartı (B.6) */
  keysTitle:'Keyboard shortcuts'}
};
